### PR TITLE
1486-webPageArchived

### PR DESCRIPTION
**Pull request by TobiasNx**
Since no there is no mapping for MAB: `051.: .w ` I tried to reconstruct this differently.
@acka47 can you have a look if this is good enough?

### CODE REVIEW

**Review by dr0i — APPROVED** [review]

**Review by acka47 — CHANGES_REQUESTED** [review]
Comparing the example with the production data, everything looks fine exsept for the type `Book` on the resource which should be removed as soon as we set the type `ArchivedWebPage`.

**Comment by TobiasNx** [comment]
> Comparing the example with the production data, everything looks fine exsept for the type `Book` on the resource which should be removed as soon as we set the type `ArchivedWebPage`.

@acka47: okay for you, if we move this to another ticket? https://github.com/hbz/lobid-resources/issues/1495
This seems to be a broader problem.

**Comment by TobiasNx** [comment]
@acka47 agreed off board to solve the problem with Books in another ticket.

**Comment by TobiasNx** [comment]
@dr0i I did this with` rebase -i` now.

**Comment by TobiasNx** [comment]
@dr0i : https://github.com/hbz/lobid-resources/pull/1490/commits/b2fee00326817a855980c66f669f3b4565d9254c This testfile is not in the master anymore?

**Pull request merged**
