### PR TITLE
868 multiple roles for agents

### LINKED ISSUE #868: Include multiple roles for agents
See MAB 100 at [HT018857620 (MAB-XML)](http://lobid.org/hbz01/HT018857620). In the json only one role is covered: http://lobid.org/resources/HT018857620.json. Because it's the first time that I saw something like this I got the confirmation by a cataloger that it's possible.

### PR DESCRIPTION
**Pull request by ChristophEwertowski**
Resolves #868

### CODE REVIEW

**Comment by dr0i** [comment]
+1

**Comment by ChristophEwertowski** [comment]
Had to fix add bugfixes, otherwise there wouldn't have been an effect which you could see in stage, e.g. the roles `StageDesign` and `ChoirTraining` wouldn't be there. Now this branch covers https://github.com/hbz/lobid-resources/issues/868, https://github.com/hbz/lobid-resources/issues/890 and https://github.com/hbz/lobid-resources/issues/903. After these many changes I didn't deployed the changes from staging to master.

**Comment by dr0i** [comment]
+1 (although the test data doesn't reflect the changes).
Going to deploy to staging at Wednesday and find resources that shows the changes.

**Comment by dr0i** [comment]
Deployed to production. See http://lobid.org/resources/HT018857620.json coverning #868,  http://lobid.org/resources/HT014882258.json covering #890 and #903 was already closed.
Closed.

**Pull request merged**
