### PR TITLE
572 update es to 5.6.3

### PR DESCRIPTION
**Pull request by dr0i**
Updates elasticsearch from 2.3 to 5.6.3.

Resolves (hopefully) #572.

### CODE REVIEW

**Comment by dr0i** [comment]
@fsteeg indexing is working albeit not via VPN yet - try e.g. `curl -L "http://weywot5.hbz-nrw.de:9200/resources-staging/resource/HT019336970"`.
The web api is not deployed yet on weywot5 because of an `NoNodeAvailableException` log entry ;)

I have updated the web api as far as I could, to the point that some `scala` tests not running ok and having trouble to analyze this. Maybe you want to have a look.

**Comment by fsteeg** [comment]
I have tweaked the Scala view code to skip missing items. The remaining failing test exposes the first actual issue: items are not found (second test in `ResponseStatusTests`: expected:<[200]> but was:<[404]>). The tests use a `NodeClient` with the embedded test index, which basically seems to work (except for the items issue).

The second issue is that the `TransportClient` (not used by the tests, used by the actual UI) does not work at all (as you mentioned: `NoNodeAvailableException`). It was still trying to connect to the ES 2 cluster on gaia and aither. I updated the config to use weywot5. It still does not work, I think because port `9300` is blocked (on weywot5? On the entire 10.x net?) `http://weywot5.hbz-nrw.de:9300/` is not accessible (Unable to connect), while `http://weywot5.hbz-nrw.de:9200/` works fine. On the old cluster, I do get a response for `http://gaia.hbz-nrw.de:9300/`, saying `This is not a HTTP port`. All of this from within the hbz, not via VPN.

Since this is now all back in Java land, can I hand this back to you at this point @dr0i?

**Comment by dr0i** [comment]
Yep - thx!

**Comment by dr0i** [comment]
Deployed to weyowt5, see e.g. `http://weywot5.hbz-nrw.de:7500/resources`.

**Comment by dr0i** [comment]
Interestingly while the lookup-test of `TT003059252:DE-5-58:9%2F041` fails the real-life lookup works: http://weywot5.lobid.org/items/TT003059252:DE-5-58:9%2F041

**Comment by dr0i** [comment]
Re my last comment: I am clueless why its working in production but not in the tests. Assigning @fsteeg.

**Comment by fsteeg** [comment]
I have no idea why, but for some reason the GetRequest does not work on the embedded test index. Using an IdsQuery works fine on both the production and the test index. I guess the GetRequest does some low-level stuff (unlike the IdsRequest, it requires the parent to be set) that does not work with our item IDs on the embedded index. So I replaced the GetRequest with an IdsQuery, see commit above.

**Comment by dr0i** [comment]
@fsteeg thx a lot!

**Comment by dr0i** [comment]
Some notes for the configuration in `elasticsearch.yml`:
- set `discovery.zen.minimum_master_nodes: 2` in . This prevents the possibility of a "split brain" by refusing indexing if not all master nodes (aka the cluster) are up. It doesn't prevent querying if a node is missing, though, which is good. 
-  set `bootstrap.memory_lock: true`  . For this to work it's crucial to set the `ulimit -l unlimited` at  OS-level.

**Comment by dr0i** [comment]
Turns out ES 5.6.3 is really slow with our data. Even when setting `mem` to 28 GB. Space one index uses with ES 2.3: 71 GB. With ES 5.6.3 : 78 GB. So there is slight (10%) more consumption.
I have the hope that the index-mapping is not well configured. That can certainly be adjusted. Also, looking at the mapping, there are a lot of fields indexed which are not meant to be there in the first place. This was also true for ES 2.3, however. Solution would be to somehow ensure well docs beeing indexed. Could imagine a post-processing which would punch the data through the `inde-config.json` so that all unexpected data would be erased.

**Comment by fsteeg** [comment]
Today weywot5 was having a high load (>12) and was responding very slowly. The stage web application, which is configured to use the weywot cluster was not responding when searching. I shut down elasticsearch on weywot5 as a first step, making the cluster (now only weywot4) responsive again.

I then took a look into the configs in `/etc/elasticsearch/elasticsearch.yml` and noticed this section:

```
# Make sure that the heap size is set to about half the memory available
# on the system and that the owner of the process is allowed to use this
# limit.
#
# Elasticsearch performs poorly when the system is swapping the memory.
```

So in `/etc/elasticsearch/jvm.options`, I've set  the heap to 16g on both weywot4 and weywot5, and restarted elasticsearch on both.

But weywot4 did not start up successfully, logging to `/var/log/elasticsearch/weywot.log`:

`memory locking requested for elasticsearch process but memory is not locked`

From reading [1] I concluded the user's memlock settings are the issue. I applied the suggested `limits.conf` settings from [2] on weywot4, restarted the machine, and elasticsearch is running. I think it's worth to try some more of the settings suggested in [2], and to apply them both on weywot4 and weywot5.

[1] https://www.elastic.co/guide/en/elasticsearch/reference/current/_memory_lock_check.html
[2] https://ozzimpact.github.io/development/elasticsearch-configuration-tuning

**Comment by dr0i** [comment]
This issue depends on #643.

**Comment by dr0i** [comment]
Re: limit
> but, other than on weywot5, this must be done every time ES is restarted. Haven't figured that out yet.

I set `MAX_LOCKED_MEMORY=unlimited` in `/etc/init.d/elasticsearch`. This should also work.  To be tested when index is buildt tomorrow.

**Comment by dr0i** [comment]
Re: ulimited memlock
> To be tested when index is buildt tomorrow.

Tested. Works.

**Pull request merged**
