### PR TITLE
FixFixError

### PR DESCRIPTION
**Pull request by TobiasNx**
Fixing monitored error 

```
990075429930206441
2023-03-11 23:57:46 +0100 [WARN] from org.metafacture.metafix.Metafix in Thread-16 - Error while executing Fix expression (at file:/home/sol/git/lobid-resources-alma/web/target/universal/stage/conf/alma/fix/relatedRessourcesAndLinks.fix, line 204): replace_all("isPartOf[].*.hasSuperordinate[].*.id", "^\\(DE-605\\)(.*)$", "http://lobid.org/resources/$1#!")
```

### CODE REVIEW

**Comment by dr0i** [comment]
There is `http://lobid.org/resources/$1#!` so something with variable substitution didn't work. Do you need more assistance?

**Comment by dr0i** [comment]
Ah, no, dump that. It's a "fix", not a wrongly transformed data.

**Comment by dr0i** [comment]
Idk - the commits are ok and build successfully ... so either you have something wrong locally or you you don't have commited the bad guy.

**Comment by TobiasNx** [comment]
Testfile that broke: https://github.com/hbz/lobid-resources/pull/1657/commits/cbd147f0a0d88ffbd2af2b7cc5b892d6c8b8f8ce

Fix for the fix: https://github.com/hbz/lobid-resources/pull/1657/commits/55a2f580cb9b4f395183e24d97fc4060653f7451

Further adjustment: https://github.com/hbz/lobid-resources/pull/1657/commits/c8fc5c7717b370c7d8a663714d020225cfd2c814

@dr0i all there.

**Comment by dr0i** [comment]
Then you have a problem locally. [This PR run's good](https://github.com/hbz/lobid-resources/pull/1657/checks).

**Comment by dr0i** [comment]
Cheez ... sorry for the confusion. You just fixed it ;)

**Review by dr0i — APPROVED** [review]

**Pull request merged**
