### PR TITLE
1341-contribution

### PR DESCRIPTION
**Pull request by TobiasNx**

### CODE REVIEW

**Comment by TobiasNx** [comment]
We are missing test data for conference but otherwise contribution should be good to go.
@dr0i could you have a look.

**Review by dr0i — COMMENTED** [review]
+1 , but we should include a test for conference

**Comment by TobiasNx** [comment]
I opened a new ticket for the test #1353.
Should we merge now and add the test later?? @dr0i

**Comment by dr0i** [comment]
As this PR introduces a new element this element should be tested, so I suggest to include directly in this branch here, keeping things in context.

**Comment by TobiasNx** [comment]
> As this PR introduces a new element this element should be tested, so I suggest to include directly in this branch here, keeping things in context.

I deleted the transformation for `"contribution"` We could merge now.

**Comment by dr0i** [comment]
> I deleted the transformation for "contribution" 

You mean `conference`.
Going to merge.

**Pull request merged**
