### PR TITLE
Replace FRBR with bibframe

### LINKED ISSUE #204: Replace FRBR "Item" class + properties with bibframe
FRBR still occurs four times in the JSON-LD context. We have already removed `frbr:Manifestation` (see https://github.com/lobid/lodmill/issues/639) and I suggest to replace the rest with Bibframe:

- http://purl.org/vocab/frbr/core#Item -> http://id.loc.gov/ontologies/bibframe/Item
- http://purl.org/vocab/frbr/core#exemplarOf -> http://id.loc.gov/ontologies/bibframe/itemOf
- http://purl.org/vocab/frbr/core#exemplar -> http://id.loc.gov/ontologies/bibframe/hasItem
- http://purl.org/vocab/frbr/core#owner -> http://id.loc.gov/ontologies/bibframe/heldBy

I guess the mapping above is correct. I had some problems with the definition of `bf:itemOf` and `bf:hasItem`, though, see http://listserv.loc.gov/cgi-bin/wa?A2=ind1702&L=bibframe&T=0&P=1431. We should wait for the response to my mail before we implement this.

### PR DESCRIPTION
**Pull request by dr0i**
This is the reopened branch which was merged and reverted in #224.
Will resolve #204.

### CODE REVIEW

**Comment by dr0i** [comment]
Deployed small test to staging, see e.g. http://test.lobid.org/resources/HT018454638?format=json.

**Comment by dr0i** [comment]
@fsteeg needs UI update as `Items` not shown in map.

**Comment by ChristophEwertowski** [comment]
@dr0i Can't test at the moment because the search doesn't work: For example http://test.lobid.org/resources/search?q=heldBy:* gives no results.
And I can't look up if I maybe did it wrong because the API documentation page throws an error. Either way the context isn't updated.

**Comment by dr0i** [comment]
@ChristophEwertowski yes you can search, e.g "http://test.lobid.org/resources/search?q=*". The `heldBy` query is probably not working yet because we changed the `items`-structure (`exemplar` vs. `hasItem` etc). and this is not yet reflected by the web app.
Re: `context.jsonld`: discussed offline with @fsteeg to not deploy it .

**Comment by ChristophEwertowski** [comment]
Then +1.

**Comment by acka47** [comment]
+1

**Comment by fsteeg** [comment]
The index config needs to be updated for what previously was `owner` and `exemplarOf`.

**Comment by dr0i** [comment]
@fsteeg I did update the index-mapping and indexed in small test. Still cannot use the API to lookup a heldBy-query. But this works:

`curl -XGET  'http://gaia.hbz-nrw.de:9200/resources-smalltest-20170224-133152/item/_search?pretty=true' -d '
{
         "query": {
         "match" : {"heldBy.id" : "http://lobid.org/organisations/DE-260"}
                  }
}'`

So again, web app needs update, no?

**Comment by fsteeg** [comment]
Commented in https://github.com/hbz/lobid-resources/issues/204#issuecomment-282340200 and reassigned that for functional review.

For this pull request: +1

**Comment by dr0i** [comment]
Merged with commit 55840eec0efe491cecbb13ca3212a145d128a053. Closing.

**Comment by dr0i** [comment]
Just a note:
`heldBy` cannot be searched for as it is in the `items` child. One can use this API call:
http://test.lobid.org/resources/search?owner=http%3A%2F%2Flobid.org%2Forganisations%2FDE-38

**Pull request closed without merging**
