### PR TITLE
1390-primaryForm

### PR DESCRIPTION
**Pull request by TobiasNx**
Both tests are needed since they include Reproduktion and Elektronische Reproduktion

Related to #1390

### CODE REVIEW

**Review by dr0i — APPROVED** [review]
+1 but if there is a chance to solve the "duplicate" question re "related" and "primary form" , it could made sense to discuss and solve that question now?

**Comment by TobiasNx** [comment]
This is a question we need to solve with @acka47 especially with regard to all linked elements. I would suggest we open another ticket with regard to the differences of these elements.

**Comment by dr0i** [comment]
ACK re new issue.

**Comment by TobiasNx** [comment]
This PR is replaced by #1403

**Pull request closed without merging**
