### PR TITLE
1977-duplicateH52

### PR DESCRIPTION
**Pull request by TobiasNx**
Fix reported error #1977

### CODE REVIEW

**Comment by dr0i** [comment]
In your first commit you have only added the XML , not the resulted JSON. In the second commit you then added the JSON. Thus no diff is possible, which was your intention I assume.
I will add the JSON to the first commit and force push so we can better see what your Fix changes.

**Comment by TobiasNx** [comment]
Nope! This is intentional, since the test breaks!!! The second commit resolves this.

**Comment by dr0i** [comment]
Yeah I see - it's not even possible to generate that JSON ;)

**Comment by dr0i** [comment]
There are conflicts - can you resolve these @TobiasNx ? I also wouldn't mind if you rebase and force push.

**Comment by dr0i** [comment]
`Build and test with Play` fails. Have a look at the README (search for `play`) . If that is not sufficiently helpful we should talk together and you would bring the README to perfection :)

**Comment by TobiasNx** [comment]
@dr0i fixed it.

**Review by dr0i — APPROVED** [review]

**Comment by dr0i** [comment]
Good :)
Will be deployed next Monday. Closed.

**Pull request merged**
