### PR TITLE
Remove meium "Electronic Resource" from online resources.

### LINKED ISSUE #212: Adjust medium information for online resources
Reported by edoweb customer C.D. on 207-02-02 (referring to the Edoweb view):

> Bei Websites steht unter „Medium“ immer „Datenträger“ und
> „Online-Ressource“. Ich glaube, da ist was falsch rübergekommen. Diese
> Information speist sich, soviel ich weiß, aus dem Feld 050 in der
> Titelaufnahme. In diesem Feld *mit der Bezeichnung* „Datenträger“ steht
> an Pos. 8 ein „g“, was bedeutet "Elektronische Ressource(n) im
> Fernzugriff“ oder „Online-Resssource“. Aber angezeigt zu werden braucht
> nur „Online-Ressource“. „Datenträger“ wäre sogar irreführend. Könnten
> Sie es so einrichten, daß da nur „Online-Ressource“ steht?

See [current moprh, line 362](https://github.com/hbz/lobid-resources/blob/c7454a6547e71f947401dc7e091107b55b2786f1/src/main/resources/morph-hbz01-to-lobid.xml#L362) where `g` is indeed included in mapping to RDA carrier type "electonic resource" (http://rdaregistry.info/termList/RDACarrierType/1010"/). We should just remove it. 

From the MAB documentation:

```

050       DATENTRAEGER

          Indikator:
          blank = nicht definiert

          Datenelemente:
...

            8  Computerdatei
               a = nicht spezifiziert
               b = Diskette(n)
               c = Magnetbandkassette(n)
               d = Optische Speicherplatte(n)
                   (z.B. CD-ROM, CD-I, Photo-CD, WORM, DVD)
               e = Einsteckmodul(e)
               f = Magnetband, Magnetbaender
               g = Computerdatei(en) im Fernzugriff
               z = sonstige Computerdatei(en)
```

### PR DESCRIPTION
**Pull request by acka47**
Fixes #212.

### CODE REVIEW

**Comment by ChristophEwertowski** [comment]
Seems right. Waiting for looking at staging system.

**Comment by dr0i** [comment]
Would love to reopened because it was accidentially merged (and undo that by force pushing the original branch again to master).
But it doesn't seem you can reopen PRs that have been closed and merged.

**Comment by dr0i** [comment]
Deplyoed to staging, see .e.g. http://staging.lobid.org/resources/HT019011249?format=json.

**Comment by acka47** [comment]
+1

**Comment by dr0i** [comment]
Deployed to production, closing.

**Pull request merged**
