### PR TITLE
Fix resolving file "institutions.tsv" (#1526)

### PR DESCRIPTION
**Pull request by dr0i**
Similar to f59c5d09ea28e20775910bcc1c5356d75fb8fda2.

See #1526.

### CODE REVIEW

**Comment by blackwinter** [comment]
Sorry, but this doesn't explain why _relative_ paths (relative to the Fix file, that is) are resolved differently in CLI and web app. The working directory is different, fine; but the directory structure is not (as you explained in #1527). And why does `include()` behave differently still? :confused: 

Also, you set both variables to the same value. How does this work?

**Comment by dr0i** [comment]
> Sorry, but this doesn't explain ...

Ack. This should be solved in [another issue](https://github.com/hbz/lobid-resources/issues/1527).
This PR here is just a quick working workaraound.

> Also, you set both variables to the same value. How does this work?

You mean
https://github.com/hbz/lobid-resources/pull/1529/files#diff-99a8a9f4045726c27c432ada7d278e20550881c5babd5ec4b2b1fcafa3197b13L2 ?
That's _two_ variables set to one location.

**Comment by blackwinter** [comment]
> Ack. This should be solved in [another issue](https://github.com/hbz/lobid-resources/issues/1527).

Okay.

> You mean
> https://github.com/hbz/lobid-resources/pull/1529/files#diff-99a8a9f4045726c27c432ada7d278e20550881c5babd5ec4b2b1fcafa3197b13L2 ?
> That's _two_ variables set to one location.

No, I meant [AlmaMarcXmlFix2lobidJsonEs](https://github.com/hbz/lobid-resources/pull/1529/files#diff-8057d2f6f68f3245d1e3843c6323177281a5f79498da99191ef40c016dcf019bR116) and [AlmaMarc21XmlToLobidJsonMetafixTest](https://github.com/hbz/lobid-resources/pull/1529/files#diff-28eb094d191f895ff3c63cee0c419ae1e0f50919e52c7809757ef129058e4743R64). But that's not even CLI vs. web app, that's CLI vs. test, right? I don't understand how this fixes anything w.r.t. the web app. But it's none of my business anyway, so I'll leave you in peace now ;)

**Review by TobiasNx — APPROVED** [review]
+1 runs locally without changes.

**Comment by dr0i** [comment]
> So you effectively only changed the path, the introduction of the variable is inconsequential?

funnily, no , it _is_ of consequence - if only the path is changed in `src/main/resources/alma/fix/maps.fix` the  commands  `mvn clean install -DskipTests=true; mvn -DgenerateTestData=true failsafe:integration-test -Dit.test=AlmaMarc21XmlToLobidJsonMetafixTest` result in:

> Caused by: org.metafacture.metamorph.api.MorphExecutionException: File not found: src/main/resources/alma/./alma/maps/institutions.tsv
        at org.metafacture.metamorph.maps.FileMap.lambda$null$0(FileMap.java:211)
        at java.util.Optional.orElseThrow(Optional.java:290)

**Comment by blackwinter** [comment]
> funnily, no , it _is_ of consequence - if only the path is changed

So you changed the path from `./maps/institutions.tsv` to `alma/maps/institutions.tsv` (on both lines) and get `File not found: src/main/resources/alma/./alma/maps/institutions.tsv`? How is this possible? Where does the `./` part come from then? It looks like we must have a serious problem somewhere...

**Comment by dr0i** [comment]
Agreed. May have also affected https://github.com/hbz/lobid-resources/actions/runs/3564501298/jobs/5989728745#step:7:557 , where the build breaks (and it does so only at GitHub, locally `mvn clean install` runs fine). This is weird.

**Comment by blackwinter** [comment]
1. I didn't understand why changing the path to `alma/maps/institutions.tsv` would work at all. But that's due to `FileMap` trying to open the path as a resource if opening it as a file fails. That's also why you saw different outcomes for maps and includes.
2. I still don't understand why your build failed. But metafacture/metafacture-fix@7635572 changed `Metafix.resolvePath()` to return an absolute path and so you should get consistent behaviour now. Of course, this also means that you have to revert your changes relying on resource search.

**Pull request merged**
