### PR TITLE
Add HOL as collection #1174

### PR DESCRIPTION
**Pull request by TobiasNx**
#1174

### CODE REVIEW

**Comment by TobiasNx** [comment]
@hagbeck is this change what you had in mind? (https://github.com/hbz/lobid-resources/issues/1174?#issuecomment-1346297758) -> every HOL gets an inCollection object.

@acka47 you wanted an example?

**Review by dr0i — APPROVED** [review]
To be honest, I don't like this:
as @acka47 noted, this bloats the data with lots of redundant entries - and `inCollection.id` is even indexed in the Elasticssearch, bloating that index too.
... but if it serves the good, go with it.

**Review by dr0i — CHANGES_REQUESTED** [review]
One thing is not correct: the id  needs a hasbang at the end like in: `http://lobid.org/organisations/DE-468#!"`

**Comment by hagbeck** [comment]
> @hagbeck is this change what you had in mind? (#1174) -> every HOL gets an inCollection object.

Yes, that the idea.

> To be honest, I don't like this: as @acka47 noted, this bloats the data with lots of redundant entries - and `inCollection.id` is even indexed in the Elasticssearch, bloating that index too. ... but if it serves the good, go with it.

You're right. This solution bloats the data. But what could be an alternative way?

**Comment by TobiasNx** [comment]
Replaced by https://github.com/hbz/lobid-resources/pull/1546

**Pull request closed without merging**
