### PR TITLE
Add "088 b" aka "item note"

### LINKED ISSUE #167: Add "Notiz" to item data
If possible, we should add "Notiz" details to our item data.

See https://github.com/hbz/lobid-resources-web/issues/15#issuecomment-271287198

### PR DESCRIPTION
**Pull request by dr0i**
Resolves #167.

### CODE REVIEW

**Comment by acka47** [comment]
+1

**Comment by fsteeg** [comment]
+1

**Comment by acka47** [comment]
Taking back my +1. I just realized that you added another "note" to the context. We already use this key. It's probably best to just remove the `skos:note`.

**Comment by ChristophEwertowski** [comment]
Wasn't fast enough. +1 if we take one note.

**Comment by dr0i** [comment]
Deployed to staging, see e.g. http://staging.lobid.org/items/TT003059252:DE-5-58:9%2F041.

**Comment by acka47** [comment]
+1

**Comment by ChristophEwertowski** [comment]
+1

**Pull request merged**
