### PR TITLE
Update Wikidata SPARQL query

### PR DESCRIPTION
**Pull request by acka47**
As discussed offline, we should update the geo index with the new query soon and will then proceed with adding ags and ks.

See hbz/lobid-vocabs#89.

### CODE REVIEW

**Comment by dr0i** [comment]
Deployed to geo_nwbib-staging (lacking "Hastenrath"). 4424 resources overall.

**Comment by acka47** [comment]
> lacking "Hastenrath"

This is strange. Running the updated SPARQL query I get both Hastenraths mentioned in https://github.com/hbz/nwbib/issues/485#issuecomment-526182027 in the results. So they should definitely be in the index.

**Comment by acka47** [comment]
> So they should definitely be in the index.

I just checked it and they are there.

**Comment by dr0i** [comment]
What I meant was lacking "Add manual matching for Hastenrath". Merged that now, will be deployed with fullindex to staging at Monday.

**Comment by dr0i** [comment]
Deployed to production, closing.

**Comment by dr0i** [comment]
Ups, the newest index wasn't build because of #1014.
Will retrigger it.

**Comment by dr0i** [comment]
Deployed to staging.

**Comment by acka47** [comment]
Please deploy to production as nearly everything looks fine now: 
- both Hastenraths ([1](http://stage.lobid.org/resources/search?q=Q1588790), [2](http://stage.lobid.org/resources/search?q=Q1271768)) are there
- nearly all previously missing spatial objects mentioned in https://github.com/hbz/nwbib/issues/485#issuecomment-526158930 are there now

But strangely, Q8249663 ("Oberbilk") ist [still missing](http://stage.lobid.org/resources/search?q=Q8249663), although it [has a NWBibID in Wikidata](https://www.wikidata.org/wiki/Q8249663) and is [in the geo index](http://weywot4.hbz-nrw.de:9200/geo_nwbib/wikidata-geo/_search?q=%22Q8249663%22). I just now added the alias "Düsseldorf-Oberbilk" to Wikidata ([diff](https://www.wikidata.org/w/index.php?title=Q8249663&type=revision&diff=1007469837&oldid=993099095)) as this is what is found in the `coverage` field. I will check whether it is in the data after the new index ishas been built on Thursday.

**Comment by dr0i** [comment]
Deployed to production, closing.

**Pull request closed without merging**
