### PR TITLE
Adjust wikidata sparql query

### LINKED ISSUE #764: Adjust Wikidata query to also cover non-administrative areas of NRW
Sub-issue of #627.

See https://github.com/hbz/lobid-resources/issues/627#issuecomment-362582753 for the list of area types to be covered.

### PR DESCRIPTION
**Pull request by acka47**
Resolves #764. I only added religious administrative territories and did some more adjustments.

### CODE REVIEW

**Comment by dr0i** [comment]
+1

**Comment by dr0i** [comment]
Deployed to index `geo_nwbib-20180417`.  Overall docs increased about 15. What is with the qualitiy? Check it out.

**Comment by acka47** [comment]
Looks quite good, except I noticed one thing: [Searching for "Kirchenkreis"](http://weywot4.hbz-nrw.de:9200/geo_nwbib-20180417/_search?q=kirchenkreis) I only get seven results, although it should be 38, see https://github.com/hbz/lobid-resources/issues/764#issuecomment-373400938. I will have to once more adjust the sparql query.

**Comment by acka47** [comment]
Didn't adjust the query but the wikidata entries that were missing "wdt:P131 wd:Q1198" statements. next time all kirchenkreise should be added to the index.

**Comment by acka47** [comment]
Please deploy and add the types to the index (#627).

**Comment by dr0i** [comment]
Deployed, closed.

**Pull request merged**
