### PR TITLE
Improve mapping for publishedScore #1669

### PR DESCRIPTION
**Pull request by TobiasNx**
Somehow also a audio record is selected as publishedScore now.

### CODE REVIEW

**Comment by blackwinter** [comment]
> Somehow also a audio record is selected as publishedScore now.

Which one are you referring to? All three test cases are mapped as "Musicalia" in our current (Aleph-based) [union catalogue](https://nrw.digibib.net/search/hbzvk).

**Comment by TobiasNx** [comment]
> > Somehow also a audio record is selected as publishedScore now.
> 
> Which one are you referring to? All three test cases are mapped as "Musicalia" in our current (Aleph-based) [union catalogue](https://nrw.digibib.net/search/hbzvk).

Have a look at: https://github.com/hbz/lobid-resources/pull/1683/commits/bc6f38457784816d725b110f8f3c95aa23d02743
I added a filter, since Hörbuch / CD and Vinyl are no `publishedScore`

**Comment by blackwinter** [comment]
> I added a filter, since Hörbuch / CD and Vinyl are no `publishedScore`

Yes, maybe `publishedScore` is not a suitable type for these cases. But we'd still like to have them mapped as some kind of "Musicalia" instead of "Miscellaneous".

**Comment by TobiasNx** [comment]
Both have wrong leaders since they are not notated music (https://alma.lobid.org/marcxml/990139686910206441): 
```
<leader>01742ncm#a2200385#c#4500</leader>
```
and https://alma.lobid.org/marcxml/990198383780206441
```
<leader>01304ncm#a2200361#c#4500</leader>
```


I agree that we should map some kind of musical recording for: http://lobid.org/resources/HT014525099#! And we could introduce a musical recording type: https://schema.org/MusicRecording

But http://lobid.org/resources/HT017775049#! is an audio book.

**Comment by TobiasNx** [comment]
Leader 6 should have been for these: 
```
i - Nonmusical sound recording
 j - Musical sound recording
```

**Comment by blackwinter** [comment]
Agreed, thank you!

**Comment by dr0i** [comment]
@blackwinter you were assigned as reviewer but I already merged it ... please have a look.

**Pull request merged**
