### PR TITLE
Change role label from Redaktor to Redaktion

### LINKED ISSUE #209: Change label from "Redaktor" to "Redaktion"
At the [example](http://lobid.org/resources/HT008589626?format=json) you can see that the role isn't translated from the [MARC relators list](http://id.loc.gov/vocabulary/relators/red.html). As acka47 said, it should be changed to "Redaktion" like in nwbib.

### PR DESCRIPTION
**Pull request by ChristophEwertowski**
Resolves #209

### CODE REVIEW

**Comment by acka47** [comment]
+1

**Comment by dr0i** [comment]
Would love to reopened because it was accidentially merged (and undo that by force pushing the original branch again to master).
But it doesn't seem you can reopen PRs that have been closed and merged.

**Comment by dr0i** [comment]
Deployed, see e.g. http://staging.lobid.org/resources/TT001671747?format=json.

**Comment by acka47** [comment]
+1


"staging" seems to be different than "beta", see http://staging.lobid.org/resources/TT001671747 vs. http://beta.lobid.org/resources/TT001671747. Is staging only a test data set?

**Comment by dr0i** [comment]
No "staging" is full new index. I never use "beta". You should also, I assume.

**Comment by fsteeg** [comment]
Beta is production (which is still in beta). Like organisations.

**Pull request merged**
