### PR TITLE
Add nwbib subject chains

### LINKED ISSUE #378: Some objects missing in `ComplexSubject`
This issue is spawned by #187:

Only one literal appears in the `ComplexSubject` where multiple literal(-objects) are in fact in the data ( field `902` and `907` have two subfields `a`), see e.g. BT000040377 ([source](http://lobid.org/hbz01/BT000040377), [JSON-LD](http://stage.lobid.org/resources/BT000040377?format=json)).

### PR DESCRIPTION
**Pull request by dr0i**
Having multiple subfields with the same name is a nwbib speciality for
cataloging subject chains which are not RSWK rule based. This was just
a workaround by nwbib catalogers. The morph shows clearly the introduced
complexity to work with these two-concepts-in-one.

- improve logging

Resolves #378.

### CODE REVIEW

**Comment by dr0i** [comment]
Deployed small test, see e.g. http://gaia.hbz-nrw.de:9200/resources-smalltest/resource/BT000040377.

**Comment by ChristophEwertowski** [comment]
+1

**Comment by dr0i** [comment]
Deployed to staging, see e.g. http://stage.lobid.org/resources/BT000040377.

**Comment by acka47** [comment]
+1

**Comment by fsteeg** [comment]
+1

**Comment by dr0i** [comment]
Deployed to production, closed.

**Pull request merged**
