### PR TITLE
Set up nested fields and nested queries

### PR DESCRIPTION
**Pull request by fsteeg**
Interpret `q` param as nested query if `nested` param is not empty, using the value of the `nested` param as the nested field path (see [1]).

Required for https://github.com/hbz/lobid-resources/issues/532 and https://github.com/hbz/nwbib/issues/163

@dr0i:
- This is based on the ES 5.6 code base
- Contains index-config.json changes that should go into the next full staging index

[1]  https://www.elastic.co/guide/en/elasticsearch/reference/5.6/query-dsl-nested-query.html

### CODE REVIEW

**Comment by fsteeg** [comment]
Great, thanks!

**Comment by dr0i** [comment]
As the weywot4-node didn't come up (see https://github.com/hbz/lobid-resources/pull/621#issuecomment-349587222 ) the indexing is started only now. Should be ready tomorrow at lunch time.

**Comment by dr0i** [comment]
Index ready as resources-staging. Not clear why number of docs roughly doubled (from 70M to 135M). Assumed this as a temporary sideeffect of the troubles described in this issue.

**Comment by dr0i** [comment]
Deployed to staging.

> why number of docs roughly doubled (from 70M to 135M).

Well, it has to be the nested fields which are internally treated as docs on their own, where: 
135m (overall) = 20m (resources) + 60m (items) + 55m (nestedFields).

**Pull request merged**
