### PR TITLE
1471-addDeleteForLookup

### PR DESCRIPTION
**Pull request by TobiasNx**
This should stop elastic search from breaking, see https://github.com/hbz/lobid-resources/issues/1471 . But does not fix the problems with the missing geo-data. This would need the solution in #1473

### CODE REVIEW

**Comment by TobiasNx** [comment]
This branch is now upbranched from #1313

**Comment by TobiasNx** [comment]
@dr0i you can go on with this one too.

**Review by dr0i — CHANGES_REQUESTED** [review]
src/test/resources/alma-fix/almaMarcXmlTestFiles is only a temporary file (it is tar.bz2 archived). I will add the removal of this file in src/test/resources/alma/updateAlmaTestFiles.sh  after the archive is created so that no traces are in the file system.

**Review by dr0i — APPROVED** [review]
Very good that you did this in two commits - one can see that before your change the lat/lon was part of the ETL.

**Pull request merged**
