### PR TITLE
200 correct zdb supplement uris

### LINKED ISSUE #200: URIs of hasSupplement lead to error
If I follow the URIs with the pattern  "http://lobid.org/resources/AA000000#!" everything is fine ([example](http://lobid.org/resources/HT017048170?format=json)). But for the data in the format "http://lobid.org/resources/ZDB-ID" errors appear ([from the periodical example of the documenation website](http://lobid.org/resources/2074003-7#!)).

### PR DESCRIPTION
**Pull request by ChristophEwertowski**
Resolves #200

### CODE REVIEW

**Comment by dr0i** [comment]
@ChristophEwertowski you should add a document which reflects the changes, otherwise this is untested and not considered stable, see https://github.com/hbz/lobid-resources/blob/master/README.textile: `Changing transformations` -> `the tested resources don’t reflect the changes.`

**Comment by dr0i** [comment]
Deployed to test.

**Comment by dr0i** [comment]
Seems that with #322 the travis build error vanished.
Do you think this is ready for deployment @ChristophEwertowski ?

**Comment by ChristophEwertowski** [comment]
For documentation: Offline I told dr0i that it was ready for deployment.

**Comment by dr0i** [comment]
Deployed to staging.

**Pull request merged**
