### PR TITLE
1864-database

### PR DESCRIPTION
**Pull request by TobiasNx**
Add mapping for type vivo:Database See #1864

### CODE REVIEW

**Review by acka47 — APPROVED** [review]
+1

**Comment by TobiasNx** [comment]
I dont know why the build does not fail, it should since I have not added Database as type to the schema yet. 

https://github.com/hbz/lobid-resources/actions/runs/10387357128/job/28760660701#step:8:68

@acka47 any idea?

**Comment by acka47** [comment]
I assume #2052 was not set up so that a failed ajv actually makes the build fail but it only added the script to the pipeline which runs the ajv test. Someone document a way to make this work with ajv and GitHub actions at https://junghyeonsu.com/en/posts/using-ajv-and-github-actions-to-ensure-consistent-meta-information-across-json-files/#integrate-ajv-with-github-actions-for-automated-validation but I am not sure what we can transfer to our use case...

**Review by maipet — APPROVED** [review]

**Comment by TobiasNx** [comment]
@Phu2 gave the hint to add an exit command to `src/test/resources/validateJsonTestFiles.sh` Did that straight to master. Now the validation should fail and I can fix the schema.

**Pull request merged**
