### PR TITLE
Improve tests, remove `stop` filter for default analyzer

### PR DESCRIPTION
**Pull request by fsteeg**
Will resolve https://github.com/hbz/nwbib/issues/506

@dr0i: This only affects the index config (except tests). Could you deploy this to (small) test and stage?

### CODE REVIEW

**Comment by dr0i** [comment]
Done, see https://test.lobid.org/resources/search?q=*.

**Comment by dr0i** [comment]
Do you really need also the "stage" for it? That would be the whole catalog, and as we have the end of the week, if the result is no good, we loose the normally fine rebuild at the beginning of the next week. What I want to say:
Please test the smalltest *before* stage-deployement.

**Comment by fsteeg** [comment]
Looks good:

http://test.lobid.org/resources/search?word=m%C3%BClheim+AND+an+AND+der+AND+ruhr
http://stage.lobid.org/resources/search?word=m%C3%BClheim+AND+an+AND+der+AND+ruhr

We get a hit on test. Could you deploy to stage?

**Comment by dr0i** [comment]
Already switched automatically to production. Seems good, see http://lobid.org/resources/search?word=m%C3%BClheim+AND+an+AND+der+AND+ruhr vs. the old one http://stage.lobid.org/resources/search?word=m%C3%BClheim+AND+an+AND+der+AND+ruhr.

**Comment by dr0i** [comment]
just a note:
yes , it was switched, but I didn't merged it into master, i.e. daily updates on production never used these commits.
Merged just now.

**Pull request merged**
