### PR TITLE
Lobid lodmill 757 exceptions bibo book videos

### PR DESCRIPTION
**Pull request by ChristophEwertowski**
Resolves https://github.com/lobid/lodmill/issues/757

### CODE REVIEW

**Comment by ChristophEwertowski** [comment]
Apparently I forgot to send the message. @dr0i : Please deploy it to staging so that the functional review can be done for the whole set of resources.

**Comment by dr0i** [comment]
@ChristophEwertowski you mean `test`, I guess. What is holding you back to index to test?

**Comment by ChristophEwertowski** [comment]
The number of affected resources. At production there are [38.000 audiovisual documents](http://lobid.org/resources/search?medium=http%3A%2F%2Fpurl.org%2Fontology%2Fbibo%2FAudioVisualDocument&aggregations=medium.id) of which 17.000 are books. At test there are only [11 audiovisual documents] so it could be that the problem consists on because of a different problem which is not covered by the added example. But since it's not very likely you can merge if you like and I'll look at it at Monday and eventually reopen another ticket (because of a different reason for the problem).

**Comment by dr0i** [comment]
Deployed to production, see e.g. http://lobid.org/resources/search?medium=http%3A%2F%2Fpurl.org%2Fontology%2Fbibo%2FAudioVisualDocument&t=book&aggregations=medium.id.

**Pull request merged**
