### PR TITLE
Update type.json

### PR DESCRIPTION
**Pull request by TobiasNx**
music was missing but was represented in the morph.

### CODE REVIEW

**Comment by acka47** [comment]
It isn't used driectly on any lobid resource, is it? See https://lobid.org/resources/search?q=type%3AMusic. Same for `SubjectHeading`, see https://lobid.org/resources/search?q=type%3ASubjectHeading.

**Comment by TobiasNx** [comment]
you are right, music is represented as PublishedScore. Should I delete SubjectHeading?

**Comment by acka47** [comment]
> Should I delete SubjectHeading?

+1

**Comment by TobiasNx** [comment]
Close, deletion of subjectHeading here: #1294

**Pull request closed without merging**
