### PR TITLE
Declare "role" a single entry, not an array

### LINKED ISSUE #132: Remove unnecessary JSON objects or add additional information
There are some properties that have an array of one or more JSON objects with only the `id` field as information. One such property is `exemplar`. As many title have a lot of items connected (see e.g. http://lobid.org/resources/HT000786420#!) the already long array gets even more bloated by the object parentheses.

Properties where this is the case: 

- `exemplar`
- `fulltextOnline`
- `hasSupplement`
- `hasVersion`
- `isFormatOf`
- `isPartOf`
- `isPrimaryTopicOf`
- `language`
- `owner`
- `sameAs`
- `seeAlso`
- `similar`
- `source`
- `tableOfContents`
- `webPageArchived`
- `description`

There are two options for dealing with these:

1. Adding additional informato the object, e.g. `type` (for exemplars this would be `Item`) or `label` if available.
2. Removing the object and directly list the URIs in the array.

Add least for `language` we should add the labels. But I doubt that we could add useful information to all of these...

### PR DESCRIPTION
**Pull request by dr0i**
Resolves #132.

### CODE REVIEW

**Comment by acka47** [comment]
+1

**Comment by ChristophEwertowski** [comment]
+1

**Comment by fsteeg** [comment]
+1

**Comment by dr0i** [comment]
Deployed to staging, see e.g. http://staging.lobid.org/resources/HT017472134.

**Comment by acka47** [comment]
+1

**Comment by ChristophEwertowski** [comment]
+1

**Pull request merged**
