### PR TITLE
1390 links

### PR DESCRIPTION
**Pull request by TobiasNx**
Related to #1390 

Builds on #1384 and #1389

### CODE REVIEW

**Review by dr0i — CHANGES_REQUESTED** [review]
+1 besides the missing test for `seeAlso`.
And the conflict, of course.

**Comment by dr0i** [comment]
There _is_ a test file which has a `seeAlso` (potentially) in it:
```
[~/git/lobid-resources/src/test/resources/alma-fix] 1390-links
 grep 585270 '(DE-605)HT018295975.xml'
```
At least this was transformed to `seeAlso` using the aleph-sources , see `src/test/resources/jsonld/HT018295975.json`.

**Comment by TobiasNx** [comment]
This seems to be an old test, this is not the productive version, see: http://lobid.org/resources/HT018295975.json

**Comment by dr0i** [comment]
Right. I searched 14GB of marc xml and couldn't find any ` <datafield tag="856" ind1="4"` .  I guess we just leave it as it is. If someone complains, we will be provided with an example :P

**Comment by dr0i** [comment]
I did a rebase on master and opened a [new PR](1393). I compared both branches and found them in sync, but @TobiasNx may want to check again. Than we could force push #1393 into this #1392 and close it.

**Pull request merged**
