### PR TITLE
Support customizable aggregations, none as default

### PR DESCRIPTION
**Pull request by fsteeg**
See https://github.com/hbz/lobid-resources-web/issues/26

Deployed to staging:

http://test.lobid.org/resources/search?q=glessen&format=json (no aggregations)
http://test.lobid.org/resources/search?q=glessen&format=json&aggregations=subject.id,owner (supported)
http://test.lobid.org/resources/search?q=glessen&format=json&aggregations=title (unsupported)

### CODE REVIEW

**Comment by ChristophEwertowski** [comment]
+1

**Comment by ChristophEwertowski** [comment]
publication.startDate and type work, too (subject.id, medium.id and owner tested for last +1). +1

**Comment by acka47** [comment]
+1 Looks good, also the error message when asking for an unsupported aggregation. I would have expected this to work, though: http://test.lobid.org/resources/search?q=glessen&format=json&aggregations=contribution.agent.id

I guess we can add useful aggregations at a later point on request by API users or when we need them.

**Comment by fsteeg** [comment]
`contribution.agent.id` is disable because it does not work, this triggered #242.

**Comment by dr0i** [comment]
+1

**Pull request merged**
