### PR TITLE
227 wrong gnd label

### LINKED ISSUE #227: Wrong URI as label for subject
See http://lobid.org/resources/BT000014215?format=json

### PR DESCRIPTION
**Pull request by dr0i**
Will resolve #227.

### CODE REVIEW

**Comment by dr0i** [comment]
See http://test.lobid.org/resources/BT000014215 vs. http://lobid.org/resources/BT000014215

**Comment by acka47** [comment]
+1

**Comment by ChristophEwertowski** [comment]
+1

**Comment by dr0i** [comment]
Deployed to production, closed.

**Pull request merged**
