### PR TITLE
Fix JSON-LD context

### LINKED ISSUE #1317: Samples not working in JSON-LD Playground
Hello! Upon trying to examine the [default sample](https://lobid.org/resources/HT018472857?format=json) given on your [API documentation page](https://lobid.org/resources/api) by using the [JSON-LD playground](https://json-ld.org/playground/), I am confronted with the following error message:
```
jsonld.SyntaxError: Invalid JSON-LD syntax; a term definition must not contain type
```

I have tried manually switching to either `JSON-LD 1.0` or `JSON-LD 1.1` parsing under `Option`; both fail with the same error. Here's a [permalink for reference](https://tinyurl.com/y5reerjg).

By contrast, both the samples from [lobid-gnd](https://lobid.org/gnd/4074335-4.json) and [lobid-organisations](https://lobid.org/organisations/DE-6?format=json) _can_ be parsed in JSON-LD playground without any problems. I suspect that something is wrong with the `context` schema at http://lobid.org/resources/context.jsonld, because its formatting looks substantially different from the schemas of [lobid-gnd](http://lobid.org/gnd/context.jsonld) and [lobid-organisations](http://lobid.org/organisations/context.jsonld). But this is just a hunch, I am not knowledgeable enough in JSON-LD to exactly put my finger on it.

Thanks for working on this project, I really appreciate that you're making all of the catalogue data openly available! :smiley:

### PR DESCRIPTION
**Pull request by acka47**
resolves #1317

### CODE REVIEW

**Review by dr0i — APPROVED** [review]

**Comment by dr0i** [comment]
Thx @acka47 ! Going to merge and deploy and let you know.

**Comment by dr0i** [comment]
Ah, no, this don't change a thing! The context is generated from the "labels", see https://github.com/hbz/lobid-resources/issues/1119.
Curious atm if it's even possible to do the wanted changes using the 'context-labels.json'.

**Comment by acka47** [comment]
I have a déjà vu

**Comment by acka47** [comment]
> Curious atm if it's even possible to do the wanted changes using the 'context-labels.json'.
I am afraid not. This is about the five entries with `"referenceType" : "http...` Apparently, when transforming this to the context it uses `type` in stea dof `@type` to indicate the data type. You will have to look into the part of the software that generates the context.

**Pull request merged**
