### PR TITLE
Fix formatting

### PR DESCRIPTION
**Pull request by acka47**
Fixes problem in https://github.com/hbz/nwbib/issues/465#issuecomment-608380737

### CODE REVIEW

**Comment by dr0i** [comment]
Going to deploy, scheduled to be finished Wednesday.

**Comment by dr0i** [comment]
Deployed to production, please review @acka47 .

**Comment by acka47** [comment]
Hmm, now those titles have no spatial at all (they should have a link to https://nwbib.de/spatial#Q10936).

**Comment by dr0i** [comment]
Hi @acka47 please have a look again, I see 56 of `Werne`, maybe the switch of the index was necessary (happened 2 hours ago).

**Comment by acka47** [comment]
To clarify, this is the goal:

For all 21 resources in http://lobid.org/resources/search?q=coverage%3A%22Werne+%7C+99%22 `spatial.id: https://nwbib.de/spatial#Q10936` should be added. But currently, no spatial at all is added based on the "Werne | 99" string, see http://lobid.org/resources/search?q=coverage%3A%22Werne+%7C+99%22+AND+NOT+_exists_%3Aspatial.

**Comment by dr0i** [comment]
Ah - there was a bug in the logic of using the string2wikidata table, resulting in log messages like these:

> WARN - Couldn't get a hit using index 'geo_nwbib-staging' querying '(Werne, Q22865 Q262166 Q253019 Q1852178 Q15632166 Q2983893 Q42744322 Q134626 Q448801 Q1548518 Q54935786)'

New index will be ready tomorrow.

**Comment by dr0i** [comment]
Deployed to staging. @acka47 please have a look.

**Comment by acka47** [comment]
+1 Please deploy.

**Comment by dr0i** [comment]
Deployed, closing.

**Pull request closed without merging**
