### PR TITLE
Delete << and >> brackets for publisher

### LINKED ISSUE #221: Puplishers with double angle brackets aren't shown correctly in HTML
Similar to https://github.com/hbz/nwbib/issues/104 where @dr0i removed the "crabs" from the data.
Example: http://lobid.org/resources/HT018147158 http://nwbib.de/HT018147158

From the JSON-LD:

```json
"publication":[
   {
      "location":"Köln",
      "publishedBy":"<<Die>> Ehrenfelder, Gemeinnützige Wohnungsgenossenschaft",
      "startDate":"2008",
      "type":[
         "PublicationEvent"
      ]
   }
]
```

### PR DESCRIPTION
**Pull request by ChristophEwertowski**
Also add new test example HT018147158.

Resolves #221.
Merge after #235.

### CODE REVIEW

**Comment by acka47** [comment]
+1

**Comment by dr0i** [comment]
Why are test files removed?

**Comment by ChristophEwertowski** [comment]
Because in the master they aren't in the hbz01XmlClobs which leads to errors if you let maven run. And if you delete the jsonld files and let them create from the XML they aren't created anymore.

**Comment by ChristophEwertowski** [comment]
+1

**Pull request merged**
