### PR TITLE
Use image only as medium

### PR DESCRIPTION
**Pull request by ChristophEwertowski**
Resolves lobid/lodmill#785 " "imageOnlyAsMedium".

### CODE REVIEW

**Comment by ChristophEwertowski** [comment]
@dr0i : Didn't include a test resource because a bug is handled in this commit which can be tested quickly. Also only 12.000 resources are affected by it. Please assign it back to me after deployment.

**Comment by ChristophEwertowski** [comment]
Sorry @dr0i, I first have to talk to acka47 about which type the maps are going to be.

**Comment by ChristophEwertowski** [comment]
Added the resource HT017066705 which contains a "PlaceOrGeographicName" which lead to this error:
```
[error] Test tests.IndexIntegrationTest.testResultCount[subject.componentList.type:
PlaceOrGeographicName] failed: expected:<2[7]> but was:<2[8]>, took 0.037 sec
```
@fsteeg / @dr0i: Where can I adjust the expected number of values?

**Comment by fsteeg** [comment]
> @fsteeg / @dr0i: Where can I adjust the expected number of values?

In general, these tests are in `lobid-resource/web/test`.

The `tests.IndexIntegrationTest.testResultCount` part of the error message contains the details: in folder `tests` you'll find a file `IndexIntegrationTest.java` which has a method called `testResultCount`. It actually uses the test data at the top, which maps queries to expected result counts (the specific query is also in the error message).

**Comment by ChristophEwertowski** [comment]
Deployed to test index. See [HT017066705 (production)](http://lobid.org/resources/HT017066705.json) / [HT017066705 (test)](http://test.lobid.org/resources/HT017066705.json).

**Comment by ChristophEwertowski** [comment]
The Github traffic lights incorrectly show that the Travis build hasn't completed. 

(By the way: "Ampel" is a much nicer word than "traffic lights".)

**Comment by ChristophEwertowski** [comment]
After resolving the conflicts the Travis tests went through. As the review doesn't require librarian knowledge I'm assigning it to @dr0i.

**Comment by dr0i** [comment]
Deployed to production, closed.

**Pull request merged**
