### PR TITLE
59 publication frequency

### LINKED ISSUE #59: Indicate journal frequency with dct:accrualPriodicity & controlled values
I just learned that there are controlled values in ZDB data for frequency information. I will investigate this so that we can also add this to the RDF.

### PR DESCRIPTION
**Pull request by dr0i**
Resolves #59.

### CODE REVIEW

**Comment by dr0i** [comment]
As discussed with @ChristophEwertowski offline we will go with it clinging directly to the root.

**Comment by dr0i** [comment]
Duplicate of lobid/vocabs#53. Closing.

**Comment by dr0i** [comment]
Would love to reopened because it was accidentially merged.
But  it doesn't seem you can reopen PRs that have been closed and merged.

**Comment by dr0i** [comment]
Deployed to staging, see e.g. http://staging.lobid.org/resources/HT010726584?format=json.

**Comment by acka47** [comment]
+1

**Comment by ChristophEwertowski** [comment]
Gave my OK already offline. Unassinging myself.

**Comment by dr0i** [comment]
Does this affects the frontend @fsteeg ?

**Comment by dr0i** [comment]
Deployed to production, as this only adds data it shouldnt' break anything.

**Comment by fsteeg** [comment]
+1 (but leave issue open, or reopen after merge, since we want to add it to the UI)

**Comment by dr0i** [comment]
Hm, cannot reopen it. Reassigning @fsteeg .

**Comment by fsteeg** [comment]
I meant the issue, which is now replaced by https://github.com/hbz/lobid-resources/issues/239, I will implement on UI level when that is deployed.

**Comment by dr0i** [comment]
ah - yes: "issue," not "pull request"

**Pull request merged**
