### PR TITLE
Fix missing describedBy

### LINKED ISSUE #710: HT019578856 missing
http://lobid.org/resources/HT019578856

### PR DESCRIPTION
**Pull request by dr0i**
Make morph rule easier to produce the mandatory rdfs:describedBy data.
There is no need to tie describedBy to creationDate.

Resolves #710.

### CODE REVIEW

**Comment by acka47** [comment]
It's `wdrs:describedby` (http://www.w3.org/2007/05/powder-s#describedby)...

**Comment by dr0i** [comment]
Uh - yes `wdrs`.

**Comment by ChristophEwertowski** [comment]
+1

**Comment by dr0i** [comment]
Deployed to production, see e.g. http://lobid.org/resources/HT019578856. Closed.

**Pull request merged**
