### PR TITLE
Document bulk download

### PR DESCRIPTION
**Pull request by dr0i**
See https://github.com/hbz/lobid-resources/issues/1073.

Done analog to https://lobid.org/gnd/api#bulk_downloads.

### CODE REVIEW

**Comment by dr0i** [comment]
Deployed to staging, see http://stage.lobid.org/resources/api.

**Comment by dr0i** [comment]
Ok, I've complemented that.

**Review by fsteeg — APPROVED** [review]

**Comment by acka47** [comment]
I removed NDJSON from the "Inhaltstpyen" paragraph as it is a pure bulk format not supporting `size` parameter and paging. Otherwise +1.

**Comment by dr0i** [comment]
Deployed to staging.
But why removing the section about setting the header to '"Accept: application/x-jsonlines"' for it _is_ supported?

**Review by acka47 — APPROVED** [review]

**Comment by dr0i** [comment]
Deployed to production, closed.

**Pull request merged**
