### PR TITLE
Add mads:componentList

### LINKED ISSUE #187: Separate subject chains from another in subject array
In https://github.com/hbz/nwbib/issues/363#issuecomment-267920766 I wrote: 

> I just remembered that we still have no way of separating two subject chains in the JSON. See for example http://test.lobid.org/resources/HT013099804.

@dr0i said in [response](https://github.com/hbz/nwbib/issues/363#issuecomment-268176121):

> As I remembered we talked about leaving the `subjectChains` as they are. If not, please make an issue and let us discuss _how_ to encode the subject chains under the `subject`-list.

I wouldn' t have brought this up again but today @larsgsvensson [made me aware over at the DINI KIM Titeldatengruppen Wiki](https://wiki.dnb.de/pages/viewpage.action?pageId=124126254) that there exists a way to express this with [MADS RDF](http://www.loc.gov/standards/mads/rdf/v1.html) which would actually not look bad in our JSON-LD. For the example document http://lobid.org/resources/HT013099804 this would look like this (only writing down the interesting parts):

```json
{
   "@context":"http://lobid.org/download/context.json",
   "id":"http://lobid.org/resources/HT013099804#!",
   "subject":[
      {
         "type":"madsrdf:ComplexSubject",
         "madsrdf:componentList":{
            "@list":[
               {
                  "id":"http://d-nb.info/gnd/4032952-5",
                  "label":"Krefeld",
                  "type":[
                     "PlaceOrGeographicName"
                  ]
               },
               {
                  "id":"http://d-nb.info/gnd/4041156-4",
                  "label":"Naherholungsgebiet",
                  "type":[
                     "SubjectHeading"
                  ]
               },
               {
                  "id":"http://d-nb.info/gnd/4125082-5",
                  "label":"Freizeitverhalten",
                  "type":[
                     "SubjectHeading"
                  ]
               },
               {
                  "id":"http://d-nb.info/gnd/4061619-8",
                  "label":"Umweltbelastung",
                  "type":[
                     "SubjectHeading"
                  ]
               }
            ]
         }
      },
      {
         "type":"madsrdf:ComplexSubject",
         "madsrdf:componentList":{
            "@list":[
               {
                  "id":"http://d-nb.info/gnd/4032952-5",
                  "label":"Krefeld",
                  "type":[
                     "PlaceOrGeographicName"
                  ]
               },
               {
                  "id":"http://d-nb.info/gnd/4041156-4",
                  "label":"Naherholungsgebiet",
                  "type":[
                     "SubjectHeading"
                  ]
               },
               {
                  "id":"http://d-nb.info/gnd/4280189-8",
                  "label":"Sportverhalten",
                  "type":[
                     "SubjectHeading"
                  ]
               },
               {
                  "id":"http://d-nb.info/gnd/4061619-8",
                  "label":"Umweltbelastung",
                  "type":[
                     "SubjectHeading"
                  ]
               }
            ]
         }
      }
   ]
}
```

### PR DESCRIPTION
**Pull request by dr0i**
- enable lists in sets
- add componentList and ComplexSubject to context

Resolves #187.

A remaining issue is #378:
E.g. BT000040377, where the field `902` has two subfields `a`, only one of those literals appear in the `ComplexSubject`.

### CODE REVIEW

**Comment by dr0i** [comment]
Deployed to staging, see e.g. http://stage.lobid.org/resources/HT015082724.

**Comment by ChristophEwertowski** [comment]
+1 Multiple component lists are also working: http://stage.lobid.org/resources/HT013099804?format=json

**Comment by acka47** [comment]
+1 Thanks for this, @dr0i! @fsteeg has to adjust the HTML as well as subjects are not shown currently, see http://stage.lobid.org/resources/HT013099804. Also, we need to adjust the subject search in "Erweiterte Suche". (Maybe it is better to wait for this until #265 is also deployed.)

**Comment by fsteeg** [comment]
+1 for the data related code changes, keeping self-assigned for UI update.

**Comment by fsteeg** [comment]
Deployed UI updates to staging:

http://stage.lobid.org/resources/HT013099804
http://stage.lobid.org/resources/HT015082724
http://stage.lobid.org/resources/search?subject=niederlande

**Comment by acka47** [comment]
+1

**Comment by ChristophEwertowski** [comment]
+1

**Pull request merged**
