### PR TITLE
38 contributor roles instead ofrelator as properties

### LINKED ISSUE #38: Don't use relators as property but indicate relator via "role" property
As discussed in #10 , we will indicate the roles of a contributor in the contributor object with the "role" property and won't use relators as properties.

Example:

``` json
{
  "@context": {
    "id": "@id",
    "type": "@type",
    "role": "http://bibframe.org/vocab/relator",
    "contributor": {
      "@type": "@id",
      "@id": "http://purl.org/dc/terms/contributor",
      "@container": "@set"
    },
    "label": "http://www.w3.org/2000/01/rdf-schema#label",
    "altLabel": "http://www.w3.org/2004/02/skos/core#altLabel",
    "subject": {
      "@type": "@id",
      "@id": "http://purl.org/dc/terms/subject",
      "@container": "@list"
    }
  },
  "@id" : "http://lobid.org/resources/HT018843259#!",
  "contributor": [ {
    "id": "http://d-nb.info/gnd/118548018",
    "type": "DifferentiatedPerson",
    "role": {
      "id": "http://id.loc.gov/vocabulary/relators/cre",
      "label": "Autor/in"
    },
    "label": "Becker, Thomas Paul",
    "altLabel": [ "Becker, Thomas P." ]
  } ],
  "subject": [ {
     "id" : "http://d-nb.info/gnd/4031485-6",
     "type": "PlaceOrGeographicName",
     "label": "Erzstift Köln",
     "altLabel": [ "Kölner Krieg", "Truchsessischer Krieg" ]
  } ]
}
```

We won't be able to only use a string as value for "role" as proposed in #10 but will – as you can see in the example – also use the [side car approach](https://github.com/hbz/lobid-rdf-to-json/issues/30) here – giving us presentation labels for the different roles in the data.

### PR DESCRIPTION
**Pull request by dr0i**
Will resolve #38 and the subtickets #128 and #129.

### CODE REVIEW

**Comment by fsteeg** [comment]
This will require coordinated changes in NWBib, where things that are now in  `contribution` are missing:

http://test.nwbib.de/HT018454638

**Comment by acka47** [comment]
@fsteeg will adjust NWBib and we will see how the changes are working out. After that I will give "+1" or ask for adjustments.

**Comment by acka47** [comment]
@dr0i, I adjusted the labels.json in [this commit](https://github.com/hbz/lobid-rdf-to-json/commit/b6eb5ac3e8f90fab5bcae81a6c635d2e74d30d91) so that MARC relators are not added to the context anymore (but the labels are still added).

**Comment by fsteeg** [comment]
+1

**Pull request merged**
