### PR TITLE
Correct spelling mistake, replace Komponist

### LINKED ISSUE #308: Correct role labels to actual roles
The labeling of the role is not consistent. For example: http://id.loc.gov/vocabulary/relators/act is correctly labeled "Schauspieler/in". But we have other roles like http://id.loc.gov/vocabulary/relators/ctg or http://id.loc.gov/vocabulary/relators/drt which are labeled "Kartographie" and "Regie" instead of "Kartograph/in" or "Regisseur/in".
Also the label for http://id.loc.gov/vocabulary/relators/ant "Basiert auf das Werk von" should be corrected.

### PR DESCRIPTION
**Pull request by ChristophEwertowski**
'Komponist' replaced by 'Komposition'.

Resolves #308

### CODE REVIEW

**Comment by dr0i** [comment]
+1

**Comment by dr0i** [comment]
Deployed to test, see e.g. http://test.lobid.org/resources/CT003012479.
If UI needs no update, reassign me for deploying.

**Comment by acka47** [comment]
+1 No UI update needed.

**Comment by dr0i** [comment]
This is already merged into master , see https://github.com/hbz/lobid-resources/commit/7e0f45b97a27c823fab6c757fccfd1f3ccd01bf3. I cannot change the base to master right now as " There are no new commits between base branch 'master' and head branch '308-correctRoleLabels' ". So I close this manually.

**Comment by dr0i** [comment]
Interestingly, after closing manually, I *can* change the base. Did so.

**Pull request closed without merging**
