### PR TITLE
164 replace bibframe1.0 uris

### LINKED ISSUE #164: Replace Bibframe 1.0 URIs
The namespace for the current Bibframe model (2.0) differs from the first Bibframe vocabulary publication (1.0). Thus, we will have to update our URIs. We have four entries in the context from the old namespace (bibframe.og):

- http://bibframe.org/vocab/contribution --> http://id.loc.gov/ontologies/bibframe/contribution
- http://bibframe.org/vocab/relator --> already covered by #142
- http://bibframe.org/vocab/agent --> http://id.loc.gov/ontologies/bibframe/agent
- http://bibframe.org/vocab/Contribution --> http://id.loc.gov/ontologies/bibframe/Contribution

### PR DESCRIPTION
**Pull request by ChristophEwertowski**
Will resolve #164

### CODE REVIEW

**Comment by ChristophEwertowski** [comment]
See #164

**Comment by dr0i** [comment]
The files in ` src/test/resources/input/nt` we needn't to revision, see 5c3b637c178741fef38e9049149c4409d4bb90c5.
Would be good to add this directory to `.gitignore` so that not accidentally these files are commited.

**Comment by acka47** [comment]
+1

**Comment by ChristophEwertowski** [comment]
Sorry, tried to rebase to the commit before adding the input/nt but it didn't work (probably because I had a file open in the editor). The fastest solution I found was resetting to the old commit and branching it. Because of that the last two commits and their history (which contain the superflous input/nt files) are lost. So I'm going to close this pull request and set up a new one (see https://github.com/hbz/lobid-resources/pull/174).

**Pull request closed without merging**
