### PR TITLE
Add Spiegel as testfile

### PR DESCRIPTION
**Pull request by TobiasNx**
Testfile for #1830

### CODE REVIEW

**Comment by TobiasNx** [comment]
@dr0i how can I increase the heapsize to get this testfile?

**Comment by dr0i** [comment]
I've [increased Java's memory to `768 MB`](56d0ff46515822273646c52d29283a174dd75697) , which seems to be sufficient at least.
Now there are some other errors, the "usual suspects" , which you can fix.

**Comment by dr0i** [comment]
> I saw that I found a solution last year in another branch.

Can you share a link to this?

[66782bb](https://github.com/hbz/lobid-resources/pull/1895/commits/66782bb1c237790a12f159503152ff8ae6bae45e) : please don't change formatting for a diff is useless then - I can't see what you have changed in essence.

**Comment by TobiasNx** [comment]
> > I saw that I found a solution last year in another branch.
> 
> Can you share a link to this?
> 
> [66782bb](https://github.com/hbz/lobid-resources/pull/1895/commits/66782bb1c237790a12f159503152ff8ae6bae45e) : please don't change formatting for a diff is useless then - I can't see what you have changed in essence.

This was the old commit, in an unused branch: https://github.com/hbz/lobid-resources/commit/d77e9bf08a438cfe13c4d622e47e75af11b475c5

I also will set the formatting back in an additional commit.

**Comment by TobiasNx** [comment]
I separated the commits for formatting, since it seems to be wrong, and the change of the heap.

**Comment by dr0i** [comment]
+1

**Pull request merged**
