### PR TITLE
Replace schema.org/publication with /PublicationEvent

### LINKED ISSUE #185: Replace schema.org/publication with schema.org/publicationEvent
publicationEvent fits more than publication. For that reason replace URIs in morph-hbz01-to-lobid and labels.json.

### PR DESCRIPTION
**Pull request by ChristophEwertowski**
Resolves #185

### CODE REVIEW

**Comment by acka47** [comment]
You overshot the mark here. We just have to replace the type `Publication` as this actually does not exist in schema.org, see http://schema.org/Publication. But http://schema.org/PublicationEvent exists. Regarding the property, there only exists http://schema.org/publication and neither http://schema.org/publicationEvent (which is a class) nor http://schema.org/publicationEvent.

Note that there is a general convention to start RDF properties in lower case and RDF classes in upper case. (Though, there are some exemptions, e.g. the RDA properties...)

**Comment by acka47** [comment]
It's strange that the type information is missing for some resources, e.g. BT000168595 and HT018585406. These are both resources where there is no `publishedBy` data. Is the addition of the type `PublicationEvent` somehow coupled to the existence of `publishedBy`? /cc @dr0i

**Comment by ChristophEwertowski** [comment]
Brought in a new commit.

**Comment by dr0i** [comment]
>  Is the addition of the type PublicationEvent somehow coupled to the existence of publishedBy?

Good catch! Indeed it is. The type is coupled to the existence of `@publisher`. As there are indeed many publications without a publisher I propose to boolean-or it with a `startDate` and with `@placeOfPublication` to be failsafe.

**Comment by dr0i** [comment]
- rebased the branch
- squashed the two commits into one
- added two commits fixing the missing type

**Comment by dr0i** [comment]
Note to myself: after deploying let's review ist again.

**Comment by dr0i** [comment]
Deployed to staging, see e.g. http://test.lobid.org/resources/BT000168595?format=json.

**Comment by acka47** [comment]
+1

**Comment by fsteeg** [comment]
+1

**Comment by ChristophEwertowski** [comment]
+1

**Pull request merged**
