### PR TITLE
1037 use https gnd uris

### PR DESCRIPTION
**Pull request by dr0i**
See #1037.

### CODE REVIEW

**Comment by dr0i** [comment]
@acka47 as always, you could fast review loking at the changed files.
This will be deployed to staging at Wednesday and going productive at Thursday if no one complains.

**Comment by acka47** [comment]
Searching the branch for `http://d-nb.info`, I get lots of hits. Most of them seem irrelevant but I am not sure about all of them, for example the Beacon stuff. Here are three examples:

https://github.com/hbz/lobid-resources/blob/63e6aec169ec89a536e8585fb240a226e966e16c/src/main/java/org/lobid/resources/RecordReaderEnhanced.java#L88

https://github.com/hbz/lobid-resources/blob/63e6aec169ec89a536e8585fb240a226e966e16c/src/main/resources/beacon/data/beacon_head.txt#L5

https://github.com/hbz/lobid-resources/blob/63e6aec169ec89a536e8585fb240a226e966e16c/src/main/resources/beacon/makePndBeacon.sh#L15

Did you take a look at all the remaining occurrences of `http://d-nb.info` @dr0i ?

**Comment by dr0i** [comment]
@acka47 you are right, these are also to be updated. Did this with the last commit. Also, removed some old api 1.0 tests. Should be good now - thx for the catch!

**Comment by dr0i** [comment]
Deployed, closed.

**Pull request merged**
