### PR TITLE
Issue 1 create repo and setup initial test

### PR DESCRIPTION
**Pull request by dr0i**
See #1.

### CODE REVIEW

**Comment by fsteeg** [comment]
A few points I noticed:

- Formatting in README: two bullet points don't render (should be `*` not `-` for .textile)
- No formatter setup yet, I'd suggest we use our current settings from the lobid repo
- To assess progress towards our goals from #1, it'd be nice to see the resulting JSON in the ES index (e.g. by printing it during the test run, or indexing it into a real ES at localhost and providing a sample query in the README)

**Comment by fsteeg** [comment]
The package name is still the old `org.lobid.lodmill`, should we use `org.lobid.resources`?

You did not adress my last point from my previous comment, right? Or did I miss something?

(To assess progress towards our goals from #1, it'd be nice to see the resulting JSON in the ES index, e.g. by printing it during the test run, or indexing it into a real ES at localhost and providing a sample query in the README)

Maybe the best would be to have some code that indexes the data into a common ES instance (like we do in the lobid-organisations repo), so we have a common result that we can look at and discuss, also with @acka47.

In general, I'd suggest we use this pull request to refine and discuss our format and approach, until we're happy. Since this is the first commit, there is no master that we diverge from, so I see no harm in a long running pull request in this case.

**Comment by fsteeg** [comment]
For consistency with the `lobid-organisations` repo, I'd suggest we:

* use `resources` (plural) as the index name
* use `resource` (singular) as the ES type

This would allow a simple, informative GET request as for organisations:

`curl "http://weywot2.hbz-nrw.de:9200/organisations/organisation/DE-605/_source" | json_pp`

Or, with a JSON plugin in the browser, we can just visit:

http://weywot2.hbz-nrw.de:9200/organisations/organisation/DE-605/_source

The anologue for resources would then look like this:

`curl "http://weywot2.hbz-nrw.de:9200/resources/resource/HT018295975/_source" | json_pp`

Or in the browser:

http://weywot2.hbz-nrw.de:9200/resources/resource/HT018295975/_source

BTW if you wrap the curl command in `@` signs, it gets code formatting in the README.

**Comment by fsteeg** [comment]
Looking at [this resource](http://weywot2.hbz-nrw.de:9200/resources/resource/HT018295975/_source), I think these would be the next steps to make it something like [this organisation](http://weywot2.hbz-nrw.de:9200/organisations/organisation/DE-605/_source):

* `compact` the JSON before storing it in ES (short keys, but `compactArrays=false`)
* remove the `@graph` structure, as we discussed today
* nested structure through framing (the current data is not framed, right?)

**Comment by dr0i** [comment]
Yes, these are next steps. There is [already an issue](https://github.com/lobid/lodmill/issues/449) for it. Let's not pack too much in this ticket.

**Pull request closed without merging**
