### PR TITLE
Use own json to get opac links

### PR DESCRIPTION
**Pull request by dr0i**
See #1915 .

### CODE REVIEW

**Comment by dr0i** [comment]
functional review: @TobiasNx 
code review: @fsteeg

**Comment by dr0i** [comment]
Deployed to stage, see e.g.  http://stage.lobid.org/resources/99371791018506441.

**Comment by TobiasNx** [comment]
+1

**Review by fsteeg — APPROVED** [review]

**Comment by dr0i** [comment]
Deployed.

**Pull request merged**
