### PR TITLE
1917 por g sublibrary location

### PR DESCRIPTION
**Pull request by TobiasNx**
Related to #1917

This PR does four things:
- add a testfile 990366624790206441
- updates the local sublibrary / libraryCode map
- adds a mapping for libraryCodes/sublibraries based on `POR $g`
- introduces a macro for adding holdingLibraries and opac links that can be used for `ITM`, `HOL` + `H52` and `POR`

### CODE REVIEW

**Review by blackwinter — CHANGES_REQUESTED** [review]
Wow, that was quick :) Thank you very much!

However, this change doesn't seem to be covered by test examples (no _new_ `hasItem.seeAlso` in d3ec19c). [990366624790206441](https://lobid.org/marcxml/990366624790206441) would be such an example.

**Comment by TobiasNx** [comment]
Now with updated libraryCode map and the suggested testfile.

**Review by blackwinter — APPROVED** [review]
:+1:

**Comment by dr0i** [comment]
Will be deployed next Monday.

**Pull request merged**
