### PR TITLE
Fix owner aggregation

### LINKED ISSUE #207: Wrong count previews in owner facet
Since owners are based on exemplar aggregations, and aggregation requests have a limited size, the owner counts are wrong (just the owners of the most frequent X exemplar, which are actually all 1). To fix this, we have to improve the efficiency of the aggregations processing to enable an aggregations request with unlimited size for exemplars.

### PR DESCRIPTION
**Pull request by fsteeg**
Will resolve #207 

This branch is deployed to staging and contains some optimizations for handling aggregations.

The actual issue however is not addressed yet, see https://github.com/hbz/lobid-resources/issues/207#issuecomment-277638981.

### CODE REVIEW

**Comment by fsteeg** [comment]
Deployed to staging, see owner facet: http://test.lobid.org/resources/search?q=bonn

**Comment by ChristophEwertowski** [comment]
+1

**Comment by acka47** [comment]
+1

**Comment by dr0i** [comment]
+1

**Comment by fsteeg** [comment]
Merged via https://github.com/hbz/lobid-resources/commit/aa19036eafa41fb8b3280133a4d0e0f8f328859d, closing.

**Pull request closed without merging**
