### PR TITLE
807 add wikidata type

### LINKED ISSUE #807: Add type to wikidata geo cache and enrich with this data
This issue is a result of https://github.com/hbz/lobid-resources/issues/627#issuecomment-362582753.

### PR DESCRIPTION
**Pull request by dr0i**
Resolves #807.

### CODE REVIEW

**Comment by fsteeg** [comment]
I'm not sure about the context of this, but mixing the existing terms and Wikidata Q-IDs in the `type` field (`"type" : [ "Location", "http://www.wikidata.org/entity/Q106658" ]`) seems weird.

**Comment by dr0i** [comment]
Seems weird to me too, but is meant only to be a temporarily workaround, yes @acka47 ?

**Comment by dr0i** [comment]
Talking with @acka47 : as we use this index only internally it's not important to be coherent. We could leave "Location" altogether or just remain all as it is. It's a nice default when lacking wikidata-entities,also.

**Comment by fsteeg** [comment]
+1

**Comment by dr0i** [comment]
Index deployed. Will be integrated into the `lobid-resources`-index when next fulldump etl is done.

**Pull request merged**
