### PR TITLE
516 add work title

### LINKED ISSUE #516: Add work title for musical score
Requested by @hagbeck via email on 2917-07-11:

> Uns ist aufgefallen, dass bei Notenwerken/Partituren der EST nicht mit
> in den lobid-Daten enthalten ist. Z.B fehlt bei HT004048199[1] der Titel
> "Rondos, Kl Orch KV 386". Dieser ist aber elementar wichtig (laut
> Fachreferenten und Musikexperten).
> 
> Wir stellen uns vor, dass der EST dann auch in einem explizit dafür
> vorgesehenen Feld abgelegt wird. Z.B. könnte das die 'unconstrained'
> Version von 'titleOfWork' (rdaw:P10088) sein: rdau:P60367 titleOfResource.
> 
> Wenn das o.ä nicht geht, hätten wir gerne den EST mindestens in
> 'alternativeTitle'. In Kombination mit 'type=PublishedScore' könnten wir
> dann diesen Fall kontrollieren.
> 
> [1] http://lobid.org/resources/HT004048199.json

For also adding this to `alternativeTitle` we would only have to add indicator `b` of `304`to [line 727 of the current morph](https://github.com/hbz/lobid-resources/blob/43d15180deaa5ddb2d1a09b1c8ad5dbe29ce7c67/src/main/resources/morph-hbz01-to-lobid.xml#L727). However, I don't think we should do it like this but rather implement the work title approach from https://github.com/lobid/lodmill/issues/784 for `304a|b`. This would result in the following JSON for the example:

```json
{
   "id":"http://lobid.org/resources/HT004048199#!",
   "title":"Konzert-Rondo A-Dur, KV 386",
   "exampleOfWork":{
      "type": "Work",
      "title":"Rondos, Kl Orch KV 386"
   }
}
```

Unfortunately, the ID for the corresponding GND work entry (http://d-nb.info/gnd/300110561) is missing in the source data , otherwise we would add it as `id` in the work object like this:

```json
{
   "id":"http://lobid.org/resources/HT004048199#!",
   "title":"Konzert-Rondo A-Dur, KV 386",
   "exampleOfWork":{
      "id": "http://d-nb.info/gnd/300110561",
      "type": "Work",
      "title":"Rondos, Kl Orch KV 386"
   }
}
```

We should probably look out for an example where the GND work ID is included...

### PR DESCRIPTION
**Pull request by ChristophEwertowski**
Resolves #516

### CODE REVIEW

**Comment by dr0i** [comment]
@ChristophEwertowski because of the recent merges there are now conflicts. Can you resolve them? In addition, can you rebase this branch to get rid of the "WIP" commit?

**Comment by ChristophEwertowski** [comment]
Did the changes from a new branch based on master. Now the conflicts are gone and there are two instead of four commits.

**Comment by dr0i** [comment]
reassigned and put into backlog , see #516.

**Comment by ChristophEwertowski** [comment]
Part of it was handled by https://github.com/hbz/lobid-resources/pull/671. The other part (the same for ind1="b") will be handled by a new branch as I'm not willing to get a branch which is over six months old up-to-date. Therefore closing this pull request. For the new pull request, see https://github.com/hbz/lobid-resources/pull/724.

**Pull request closed without merging**
