### PR TITLE
Remove empty subject objects

### PR DESCRIPTION
**Pull request by ChristophEwertowski**
Resolves https://github.com/hbz/lobid-resources/issues/569

### CODE REVIEW

**Comment by ChristophEwertowski** [comment]
Deployed to test. See [HT018295975 (production, json)](http://lobid.org/resources/HT018295975.json) / [HT018295975 (test, json)](http://test.lobid.org/resources/HT018295975.json).

**Comment by dr0i** [comment]
+1 nice!

**Comment by acka47** [comment]
Very nice. As @fsteeg writes in https://github.com/hbz/lobid-resources/issues/569#issuecomment-363764907 we have the 
> Same issue in `isPartOf` and `publication`, see http://lobid.org/resources/HT019582722.json

Please also fix those.

**Comment by dr0i** [comment]
Deployed to prodcution, closed.

**Pull request closed without merging**
