### PR TITLE
Remove Twitter; use Mastodon (#1859)

### PR DESCRIPTION
**Pull request by dr0i**
See #1859.

- update fontawesome to 6.4.2 (gains mastodon) by copy new css to old css
- add new webfonts
- remove old fontawesome fonts
- refactor "fa" (fontawesome) to "fa-brands" for brands (github and twitter)

Like https://github.com/hbz/lobid/pull/516.

### CODE REVIEW

**Comment by dr0i** [comment]
Deployed to http://stage.lobid.org/resources @acka47 for functional review.

**Review by acka47 — APPROVED** [review]
+1

**Comment by dr0i** [comment]
Ready for functional review @acka47 see http://stage.lobid.org/resources .

**Comment by dr0i** [comment]
Assigning @sroertgen for code review.

**Comment by dr0i** [comment]
Deployed to https://lobid.org/resources , closed.

**Pull request merged**
