### PR TITLE
Remove title from 331 and 085, add title from 331 and 360

### PR DESCRIPTION
**Pull request by ChristophEwertowski**
Resolves https://github.com/hbz/lobid-resources/issues/672

### CODE REVIEW

**Comment by ChristophEwertowski** [comment]
Added to test. See [HT016138627 (test, json)](http://test.lobid.org/resources/HT016138627.json).

**Comment by ChristophEwertowski** [comment]
Now it should be fine. See [HT016138627 (json, test)](http://test.lobid.org/resources/HT016138627.json).

**Comment by dr0i** [comment]
+1

**Comment by ChristophEwertowski** [comment]
Removed **deweyLabels.tsv** from src/main/resources.

**Comment by dr0i** [comment]
Deployed to production, see  http://lobid.org/resources/HT016138627. 
Closed.

**Pull request merged**
