### PR TITLE
Replace Mapbox-based MakiMarkers with local default icon

### LINKED ISSUE #1966: Map markers don't load
Same as https://github.com/hbz/nwbib/issues/637

### PR DESCRIPTION
**Pull request by fsteeg**
Will resolve #1966, see e.g. http://stage.lobid.org/resources/990182586200206441

(And two other tweaks for things I noticed.)

### CODE REVIEW

**Review by dr0i — CHANGES_REQUESTED** [review]
Code ok , but the marker cannot be loaded as only ./web/public/javascripts/images/marker-icon-2x.png exists but it wants ./web/public/javascripts/images/marker-icon.png .

**Comment by fsteeg** [comment]
That's weird, I actually had to rename the file since it wanted `marker-icon-2x.png`, not `marker-icon.png`. And I thought it was working when I deployed earlier. Will look into it.

**Comment by fsteeg** [comment]
Oh, I think I understand: my office screen is high-res, and I might have some scaling enabled on the OS level. So there, it requests the `2x` version, so it worked when I tested and deployed it earlier. Now, on my home setup, I get the same error as you. Will add the other icon.

**Comment by fsteeg** [comment]
Deployed to test: http://test.lobid.org/resources/990182586200206441

(If you want, you could deploy to prod and stage if this is done and there is anything unusual to consider for deployment.)

**Review by dr0i — APPROVED** [review]

**Pull request merged**
