### PR TITLE
Prioritize AlmaMmsId for opac links #1888

### PR DESCRIPTION
**Pull request by TobiasNx**
Related to #1888

I talked to @eschackmann to prioritize the opac links. 

1. almaMmsId
2. zdbId
3. hbzId

Also I excluded ISSN/ISBN opac link mappings since they are not needed yet. Updated versions of link lists are empty.

### CODE REVIEW

**Review by dr0i — CHANGES_REQUESTED** [review]
Due to the reformatting one cannot identify the real places of change. Could you separate formatting and coding by providing two commits?

**Comment by TobiasNx** [comment]
Done @dr0i  but merge #1928 first into the master :)

**Comment by TobiasNx** [comment]
> Due to the reformatting one cannot identify the real places of change. Could you separate formatting and coding by providing two commits?

This is done by #1928

**Review by dr0i — APPROVED** [review]

**Comment by dr0i** [comment]
Will be deployed next Monday.

**Pull request merged**
