### PR TITLE
1797-zdbIdSpace

### PR DESCRIPTION
**Pull request by TobiasNx**
Sometimes zdbId can have values like `2598795 1`. The whitespace should be substituted with an `-`.

### CODE REVIEW

**Review by dr0i — CHANGES_REQUESTED** [review]
What is the purpose of this PR -  order is afaik nothing we support. Order is arbitrary.
And why intoducing a new test file?

**Comment by TobiasNx** [comment]
Have a look at the commits not just the diff, the new test fixes the problem with the space.

**Comment by dr0i** [comment]
Ok, but I beg for a simple description - it's easier for you who has understanding of the problem.
Leaving the order: why change it?

**Comment by TobiasNx** [comment]
The reason is it enables to group the `replace_all` fixes for `zdbId` together in the last commit. It is a preparation for the last commit.

**Pull request merged**
