### PR TITLE
adjust urn regex

### PR DESCRIPTION
**Pull request by maipet**
#2034

### CODE REVIEW

**Review by fsteeg — COMMENTED** [review]
Updated the web app tests for the new test data to fix the build.

Looking at the code I'm wondering if the match-regex shouldn't be the same as the replace-regex, to make sure it is actually replaced if it matches? But will assign @TobiasNx for proper functional review.

**Comment by TobiasNx** [comment]
Functionally this looks good. Next time combine the changes in the  Fix and the changes in the testfiles in one commit.

Otherwise is this hint from @fsteeg a must? Is there a scneario where there is a urn without http?

> Looking at the code I'm wondering if the match-regex shouldn't be the same as the replace-regex, to make sure it is actually replaced if it matches?

Otherwise +1

**Comment by TobiasNx** [comment]
We talked about it off board, lets try to create the urn and the resolver links differently:

Fetch all urn from the links AND copy all urn links that are marked Resolver-System in $x without formatting except doi links.

**Comment by TobiasNx** [comment]
@maipet I added some commits to better handle the URNs and Resolver Links. The links in 865 with Resolver System were already used but were skipped if they had a `nbn` refrence in them. I specified the regex pattern a little bit more and decoupled the URN links in 865 from the URN in 024 and I only use the URN from 024 as fallback for links.

Additionally I have changed the URL for nbn links to org instead of de since that seems to be the standard.

**Comment by TobiasNx** [comment]
This pr is replaced by #2043

**Pull request closed without merging**
