### PR TITLE
1248 remodel contributor roles

### PR DESCRIPTION
**Pull request by TobiasNx**
- this PR takes up all existing creator roles as given in the source data
- it introduces an separate labels file for marcRel
- maps Author, Verfasser, auth. and marcRel aut to marcRel aut (ALEPH)
- changes some minor labels
- sets as explained below the default marcRel of 100|110 to aut analog to the convention of the ALMA-Transformation (ALEPH)

Concerning the default value aut:

> Here is a quick solution that would adapt the mapping rule of ALEPH to ALMA of the hbz:
> 
> https://service-wiki.hbz-nrw.de/pages/viewpage.action?pageId=483000321
> 
>         Geistige Schöpfer (Person)
> 
>         $$4 wenn nicht vorhanden per Default mit "aut" belegt
> 
> It then would reproduce the data and the convention of the Verbundskatalog. It also would not really change the aut labels of all the default entries. This would then not trigger big changes in the GUI of lobid or nwbib since most cre which is was default and was mapped from aut is also labeled Autor/in.
> 
> Though it would change the id of the default marcRel to aut. But since the labels and not the id's seem to be queried i think that this would not be such a problem.

### CODE REVIEW

**Comment by dr0i** [comment]
There are conflicts, please resolve them first.

**Review by acka47 — APPROVED** [review]
I pushed some adjustments with b3df387. (Feel free to revert those that are not correct.) Otherwise +1.

**Comment by TobiasNx** [comment]
There should be no conflicts here anymore

**Comment by dr0i** [comment]
There was a failing Aleph API test - updated that.

**Comment by dr0i** [comment]
See e.g. https://alma.lobid.org/resources/search?q=HT000161712&format=json.
Closed.

**Pull request merged**
