### PR TITLE
Remove bibo:volume.

### LINKED ISSUE #8: Remove obsolete properties
We have a workaround `lv:nameOfContributingCorporateBody` (introduced with hbz/lobid#38), where we subsume literals of corporate bodies, be they creators or contributors. I think this property will be made obsolet by the new `lv:contributorOrder` , right?

### PR DESCRIPTION
**Pull request by acka47**
Fixes #8. See https://github.com/hbz/lobid-resources/issues/8#issuecomment-273803625.

### CODE REVIEW

**Comment by dr0i** [comment]
+1

**Comment by ChristophEwertowski** [comment]
+1

**Comment by acka47** [comment]
This is now ready to be deployed by @dr0i .

**Comment by dr0i** [comment]
Deployed to staging, see http://test.lobid.org/resources/HT003654516.

**Pull request merged**
