### PR TITLE
Add missing predecessors and successors

### PR DESCRIPTION
**Pull request by ChristophEwertowski**
Predecessors and successors added for 780 and 785 (RDA).
Predecessors and successors added for 531 and 533 (RAK)
without hbzIds.

Resolves https://github.com/hbz/lobid/issues/137 (not resources 137)

### CODE REVIEW

**Comment by ChristophEwertowski** [comment]
See [HT006853428 (json at test)](http://test.lobid.org/resources/HT006853428.json) for a predecessor without a hbz-Id/URL. See [HT018138676 (json at test)](http://test.lobid.org/resources/HT018138676.json) for RDA predecessor and successor at MAB 780 and 785.

**Comment by dr0i** [comment]
@ChristophEwertowski can you resolve the conflicts? tar xfz the tar.bz2 in a clean directory, git co master, then tar xfz that tar.bz2 in the same directory. After that: tar cfj hbz01XmlClobs.tar.bz2 $dir

**Comment by dr0i** [comment]
+1

**Comment by dr0i** [comment]
Deployed to production, see http://lobid.org/resources/HT006853428.json and http://lobid.org/resources/HT018138676.json. Closed.

**Comment by ChristophEwertowski** [comment]
`predecessor` and `successor` are missing!

**Comment by dr0i** [comment]
No that's just the cache of the web app, try the index directly `curl 'http://weywot5.hbz-nrw.de:9200/resources/resource/HT006853428' |grep predecessor`.

**Comment by ChristophEwertowski** [comment]
Alright.

**Comment by dr0i** [comment]
Ok, it don't hurt to also always restart the web app - this is also easy because we have a load-balancer.
Yeah will do that from now on.

**Pull request merged**
