### PR TITLE
265 add source of subject

### LINKED ISSUE #265: Use generic approach for subject information
This originates from #187. 

Generally, we have the problem that the catalog provides subject information from different authority files and classifications. We started with GND subjects in lobid and later added DDC, NWBib subjects and RPB subjects. There are still a lot of subjects that don't get into the RDF (e.g. RVK and MeSH). We should use a generic approach for the subject headings that enables us to later add missing subjects. This approach should also cover NWBib and RPB which we created specific properties for in the past. 

A good example is http://lobid.org/resources/HT015305889#! as it has subject information from four different sources: RPB, NWBib, GND and DDC. Currently, this looks like follows (snippets).

[Source](http://lobid.org/hbz01/HT015305889):

```xml
<datafield tag="700" ind1="l" ind2="1">
  <subfield code="a">rpb824020</subfield>
</datafield>
<datafield tag="700" ind1="l" ind2="1">
  <subfield code="a">550</subfield>
</datafield>
<datafield tag="700" ind1="l" ind2="1">
  <subfield code="a">130</subfield>
</datafield>
<datafield tag="700" ind1="b" ind2="1">
  <subfield code="a">780</subfield>
</datafield>
<datafield tag="700" ind1="n" ind2="1">
  <subfield code="a">99</subfield>
  <subfield code="b">Köln</subfield>
</datafield>
<datafield tag="700" ind1="n" ind2="1">
  <subfield code="a">824040</subfield>
</datafield>
<datafield tag="902" ind1="-" ind2="1">
  <subfield code="p">Bares, Peter</subfield>
  <subfield code="d">1936-2014</subfield>
  <subfield code="9">(DE-588)13163514X</subfield>
</datafield>
```

[JSON-LD](http://lobid.org/resources/HT015305889?format=json):

```json
{
  "@context" : "http://lobid.org/download/context.json",
  "id" : "http://lobid.org/resources/HT015305889#!",
  "nwbibSubject" : [ {
    "id" : "http://purl.org/lobid/nwbib#s824040",
    "label" : "Komponisten"
  } ],
  "rpbSubject" : [ {
    "id" : "https://w3id.org/lobid/rpb2#n550",
    "label" : "Musik"
  }, {
    "id" : "http://purl.org/lobid/rpb#n824020",
    "label" : "Instrumentalmusiker"
  }, {
    "id" : "https://w3id.org/lobid/rpb2#n130",
    "label" : "Landeskunde Region Koblenz"
  } ],
  "subject" : [ {
    "dateOfBirth" : "1936",
    "dateOfDeath" : "2014",
    "id" : "http://d-nb.info/gnd/13163514X",
    "label" : "Bares, Peter",
    "type" : [ "Person" ]
  }, {
    "id" : "http://dewey.info/class/780/",
    "label" : "Musik"
  } ]
}
```

Generally, I propose to represent this in JSON-LD as follows (with `source` mapped to [`bf:source`](http://id.loc.gov/ontologies/bibframe/source)):

```json
{
  "@context" : "http://lobid.org/download/context.json",
  "id" : "http://lobid.org/resources/HT015305889#!",
  "subject" : [ {
    "dateOfBirth" : "1936",
    "dateOfDeath" : "2014",
    "id" : "http://d-nb.info/gnd/13163514X",
    "label" : "Bares, Peter",
    "type" : [ "Person" ],
    "source": "http://www.wikidata.org/entity/Q36578"
  }, {
    "id" : "http://dewey.info/class/780/",
    "label" : "Musik",
    "source": "http://www.wikidata.org/entity/Q48460"
  },
  {
    "id" : "https://w3id.org/lobid/rpb2#n550",
    "label" : "Musik",
    "source": "https://w3id.org/lobid/rpb2"
  }, {
    "id" : "http://purl.org/lobid/rpb#n824020",
    "label" : "Instrumentalmusiker",
    "source": "https://w3id.org/lobid/rpb2"
  }, {
    "id" : "https://w3id.org/lobid/rpb2#n130",
    "label" : "Landeskunde Region Koblenz",
    "source": "https://w3id.org/lobid/rpb2"
  },
  {
    "id" : "http://purl.org/lobid/nwbib#s824040",
    "label" : "Komponisten",
    "source": "http://purl.org/lobid/nwbib"
  }
 ]
}
```

For GND subject chains, we should add a `madsrdf:ComplexSubject` like proposed in #187. The last open question would then be what to do with single GND/RSWK subjects like in the example used here. There are two options:

1. Always create a `madsrdf:ComplexSubject` for GND/RSWK subjects, even if there is only one.
2. Make an exemption for single GND/RSWK subjects and add them to the subject array like in the proposed outcome above.

### PR DESCRIPTION
**Pull request by dr0i**
Will resolve #265.

### CODE REVIEW

**Comment by dr0i** [comment]
Deployed to test, see e.g. http://test.lobid.org/resources/HT018617137.

**Comment by acka47** [comment]
I made three additional changes (directly on GitHub). @dr0i, as you are on it anayway, could you please adjust the test files?

**Comment by acka47** [comment]
The rest looks fine to me.

**Comment by dr0i** [comment]
Thx @acka47 for the catches. Updated the files. Stage deployment as always at monday.

**Comment by ChristophEwertowski** [comment]
+1

**Comment by dr0i** [comment]
Note that when subjects are cataloged as just plain text, without any provenance information, the "source" field is simply omitted, see e.g. http://lobid.org/resources/BT000040377?format=json

**Comment by dr0i** [comment]
Deployed to production, closed.

**Pull request merged**
