### PR TITLE
773 add license statement

### LINKED ISSUE #773: Add copyright statement
A publisso customer needs the copyright statement which can be found in MAB 444. For an example look at [HT019488427 (MAB-XML)](http://lobid.org/hbz01/HT019488427):
```
<datafield tag="444" ind1="a" ind2="1">
   <subfield code="n">Sofern nicht anders angegeben, ist dieses Werk lizenziert unter einer Creative Commons Namensnennung 4.0 Lizenz</subfield>
   <subfield code="u">https://creativecommons.org/licenses/by/4.0/</subfield>
</datafield>
```

I'm going to look how many entries are in our data and what subfields MAB 444 can contain. According to the collegues from the BVB the field is called "Informationen zum Copyright-Status" and is a RDA field.

Original issue: https://jira.hbz-nrw.de/browse/FRL-267

### PR DESCRIPTION
**Pull request by ChristophEwertowski**
Resolves #773

### CODE REVIEW

**Comment by dr0i** [comment]
@acka47 and @ChristophEwertowski:
Everytime a new field is introduced we must also update the `index-config` _if_ the field should be searchable. If not, all is done .
I could imagine here to want to query `license.id` to filter all CC0 , CC-By etc.

**Comment by ChristophEwertowski** [comment]
The request was just about to be able to show the license information but I also think it would be nice to be able to query the `license.id`. What do you think, @acka47 ?

**Comment by acka47** [comment]
+1 for indexing `license.id`.

**Comment by ChristophEwertowski** [comment]
Added `license.id` to the index-config.json.

**Comment by dr0i** [comment]
+1

**Comment by dr0i** [comment]
Deployed to production, see e.g. http://lobid.org/resources/HT019488427.json. Closed.

**Pull request merged**
