### PR TITLE
Update query param for advanced search over all fields

### LINKED ISSUE #222: Query not inserted in search bar
With active facets, e.g.:

http://lobid.org/resources/search?q=k%C3%B6ln&issued=1462-1842&owner=http%3A%2F%2Flobid.org%2Forganisations%2FDE-38 (`köln` missing in search bar)

### PR DESCRIPTION
**Pull request by fsteeg**
Will resolve #222.

Deployed to staging, see `köln` in search bar for:
http://test.lobid.org/resources/search?q=k%C3%B6ln&issued=1462-1842&owner=http%3A%2F%2Flobid.org%2Forganisations%2FDE-38

### CODE REVIEW

**Comment by ChristophEwertowski** [comment]
+1 It's also good that the "Alles" dropdown entry is shown anymore.

**Comment by acka47** [comment]
+1

**Comment by dr0i** [comment]
+1

**Comment by fsteeg** [comment]
Merged via https://github.com/hbz/lobid-resources/commit/2ac44ebcc434ce3cf64f79b34815eeea17db7854, closing.

**Pull request closed without merging**
