### PR TITLE
Add string2wikidata map

### PR DESCRIPTION
**Pull request by acka47**
Fixes https://github.com/hbz/lobid-resources/issues/880

@dr0i There are 14 (`$ grep -Pv "\t" src/main/resources/string2wikidata.tsv | wc -l`) entries where there is no QID available. I decided to have them in the file anyway to have an overview what is missing. Just so you know if this may cause trouble processing it.

### CODE REVIEW

**Comment by dr0i** [comment]
Looks good, taking over to implement lookup/enrichment mechanism.

**Comment by dr0i** [comment]
Deployed to staging. 
Now ~6k more with `spatial.id`, see https://test.nwbib.de/search?location=&q=spatial.id%3A* . 
Generated statistics here http://stats.lobid.org/scoreCoverageCsv_alleWerte.csv.
A score of `1.0` is most likely a match of the manually generated Qid-map. `1.0` because it's not exactly a search but rather an id-lookup done in elasticsearch.
Assigning @acka47 for review.

**Comment by acka47** [comment]
+1

**Comment by dr0i** [comment]
Deployed to production, closed.

**Pull request merged**
