### PR TITLE
50 is part of name

### LINKED ISSUE #50: Use "isPartOf" with bnode instead of "isPartOfName"
Example: http://lobid.org/resources/HT018771475

Currently it looks like this:

``` json
"id":"http://lobid.org/resources/HT018771475",
"isPartOfName":[
   "Classic cars"
]
```

Should look like this instead:

``` json
"id":"http://lobid.org/resources/HT018771475",
"isPartOf": [ {
   "label":  "Classic cars"
} ]
```

### PR DESCRIPTION
**Pull request by dr0i**
Merge after #147.

Resolves #50.

### CODE REVIEW

**Comment by dr0i** [comment]
Deployed to staging, see http://test.lobid.org/resources/HT018771475.

**Comment by acka47** [comment]
+1

**Comment by dr0i** [comment]
Would like to deploy to production if @fsteeg gives +1.

**Comment by fsteeg** [comment]
+1

**Comment by dr0i** [comment]
Deployed.

**Pull request merged**
