### PR TITLE
Replace ISBD for bibframe **extent** property

### LINKED ISSUE #229: Replace isbd:extent with bf:extent
Update morph and labels.json: http://iflastandards.info/ns/isbd/elements/P1053 -> http://id.loc.gov/ontologies/bibframe/extent

### PR DESCRIPTION
**Pull request by ChristophEwertowski**
Resolves #229 

(It seems, styling with Markdown is not supported everywhere...)

### CODE REVIEW

**Comment by dr0i** [comment]
+1

**Comment by ChristophEwertowski** [comment]
New commit to erase the conflicts.

**Comment by acka47** [comment]
+1

**Comment by ChristophEwertowski** [comment]
Because it was faster than rebasing I branched from the current master and repeated the process of replacing the URLs. Now it has got no conflicts anymore but it fails a test. Any ideas, @dr0i ?

**Comment by ChristophEwertowski** [comment]
Conflicts solved, unassigning myself.

**Pull request merged**
