### PR TITLE
1071 related note and isbn

### LINKED ISSUE #1071: Add relation information to "related" objects
This originates in a thread on the NWBib mailing list starting 2020-06-15 and named "Fwd: Feedback zu NWBib...". NWBib editors want the links to related resources from fields `527`, `775` und `776` shown in NWBib with the label from subfield `n` (at least for `776`). I.N. writes today (2020-06-22):

> wenn es für Sie leicht umzusetzen ist, die URL aus dem Feld "related" in die Nutzeroberfläche einzubinden, würden wir das Angebot gerne annehmen. Als Hinweistext sollte man die üblichen Bemerkungen aus dem Unterfeld "n" des Feldes 776 verwenden:  "Online-Ausgabe" bzw. "Druck-Ausgabe".

I.N. was responding to my email from 2020-06-17:

> wir haben die Links momentan bereits schon in den JSON-Daten unter 
> "related", siehe z.B. http://lobid.org/resources/HT020163348.json:
> 
> "related": [
>    {
>      "id": "http://lobid.org/resources/HT020163372#!",
>      "label": "Der Prozess der Berufsorientierung aus der Perspektive 
> der Schülerschaft mit sonderpädagogischem Unterstützungsbedarf im 
> Bereich Lernen an Förderschulen im Land Nordrhein-Westfalen"
>    }
> ]
> 
> Allerdings sind unter "related" auch Verweise aus den Feldern 527, 775 
> und 776 zu finden. Wir holen dafür die ID der verlinkte Ressource aus 
> Unterfeld 9 und das Label aus Unterfeld t bzw. bei 527 Unterfeld a. Die 
> Unterfelder i, n und a werden also bisher bei der Datentransformation 
> nicht berücksichtigt.

For reference, the links were added with #367 .

### PR DESCRIPTION
**Pull request by TobiasNx**
This should also fix #1071 for ALMA-Fix.

### CODE REVIEW

**Review by dr0i — APPROVED** [review]

**Comment by acka47** [comment]
I stumbled over the note field with content "Reproduktion von", see [src/test/resources/alma-fix/990118562160206441.json](https://github.com/hbz/lobid-resources/pull/1501/files#diff-18b54b90480f004777d68ffccbe96464b39d4c0dc16483f6534b4e3c1a3fb2e5)

Looking at the MARC data, this should rather be represented as a relation (maybe with `isFormatOf`?) between two lobid resources

<datafield tag="776" ind1="0" ind2="8">
<subfield code="i">Reproduktion von</subfield>
<subfield code="k">Bundesanzeiger ; Jg. 54, Nr. 92a</subfield>
<subfield code="w">(DE-605)HT013365271</subfield>
</datafield>

**Comment by acka47** [comment]
There is a similar problem here like with the `license` not reccently. See e.g.: 

https://github.com/hbz/lobid-resources/blob/b4adf01e9ac2f58f3ccbfbfc3f1f7bdcd4a07008/src/test/resources/alma-fix/990193806600206441.json#L62-L66

The note is actually a note on the4 _relation_ of the two resources but as we put it now, it is a note on the linked resource itself. I only see one option to solve this without an API break: Leave out the note in the transformation.

However, for some relations, we do have a specific property (which can be viewd as kind of sub-properties of `related`).

- for links to reproductions we could use `hasVersion` (and reproductions can link back with `primaryForm`)
- for links to "Online-Ausgabe" we could use `fulltextOnline`

**Comment by TobiasNx** [comment]
>     * for links to reproductions we could use `hasVersion` (and reproductions can link back with `primaryForm`)

unfortunatly `hasVersion` is not that narrow:
https://github.com/hbz/lobid-resources/blob/97edd442892d26788ed1b93e0fe2e30237d600a4/src/main/resources/morph-hbz01-to-lobid.xml#L6905-L6931

it is a dump for all related links unless urn, doi, Volltext, ToC or description: https://github.com/hbz/lobid-resources/issues/1242#issuecomment-833305273
Also see our discussion hhere: https://github.com/hbz/lobid-resources/issues/1367

We intended to stop using `hasVersion` for now.

**Comment by TobiasNx** [comment]
Model `"note"` without prefix.

**Comment by TobiasNx** [comment]
I deleted "Erscheint auch als" and did not exclude $i completly since some format/medium info for note is sometimes placed there. I also open another ticket for cleaning up "related" since there is duplicate info e.g. with `primarySource` and `fulltextonline` and others.

**Comment by acka47** [comment]
@TobiasNx can you please add some example MARC21 XML?

**Comment by TobiasNx** [comment]
> @TobiasNx can you please add some example MARC21 XML?

@acka47 we do not need your example here just your review :)

**Review by acka47 — APPROVED** [review]
+1 Sorry for the confusion in the comments.

**Comment by TobiasNx** [comment]
@dr0i could you merge?

**Comment by dr0i** [comment]
Merged. Will be deployed next week. Closing.

**Pull request merged**
