### PR TITLE
Replace rda for bibframe supplement

### PR DESCRIPTION
**Pull request by dr0i**
See #230.

Deployed small test set to staging , see e.g. http://test.lobid.org/resources/HT000009600?format=json.

Note that @fsteeg and me decided offline not to deploy the context (at http://test.lobid.org/resources/context.jsonld) so you have to look in the commit for the changes in context.

### CODE REVIEW

**Comment by ChristophEwertowski** [comment]
+1

**Comment by acka47** [comment]
+1

**Comment by fsteeg** [comment]
First, https://github.com/hbz/lobid-resources/pull/248#issuecomment-281306129 applies here too.

Second, I see a change that I think we did a long time ago (array changes in http://lobid.org/resources/HT013480902?format=json, which does not have arrays for agent and title, but the diff shows that, see https://github.com/hbz/lobid-resources/pull/262/files#diff-a028cb038fe59ff798780bcd141e353b).

Then there are the context changes, which I reviewed in https://github.com/hbz/lobid-resources/issues/237#issuecomment-281315619.

For `hasSupplement` -> `supplement`: +1

**Comment by dr0i** [comment]
Re: second:
Only one resource is affected, and it was one old resource that newer got updated because the json-comparator checks if the content is changing only, not syntax. So that test resource just now changed in content (different context location) and that got triggered the rebuild of the resource as one would now expect.

**Pull request merged**
