### PR TITLE
Change related.issn to array and delete - #1828

### LINKED ISSUE #1828: ISSN with -
`-` needs do be deleted  in ISSN: http://lobid.org/resources/99370698912306441

Based on Issue in JIRA bei Fachrepositorium Lebenswissenschaften.

### PR DESCRIPTION
**Pull request by TobiasNx**
Resolves #1828

ISSN is defined as array in the context therefore I changed related.issn to an array.
https://github.com/hbz/lobid-resources/blob/3b710e2b2212bedea139d83da4655033c67fea08/web/conf/context.jsonld#L89-L92

Also it has a - which should be deleted.

### CODE REVIEW

**Comment by TobiasNx** [comment]
```
[error] Test tests.IndexIntegrationTest.testResultCount[(83) {Q=q.all:07206763}] failed: expected:<[0]> but was:<[1]>, took 0.076 sec
...
[error] Test tests.IndexIntegrationTest.testResultCount[(84) {Q=q.all:0720\-6763}] failed: expected:<[1]> but was:<[0]>, took 0.091 sec
```

@blackwinter These are your tests. I have deleted the `-` in related.issn and turned issn into an array as defined in the context.
Could you have a look?

**Comment by TobiasNx** [comment]
@dr0i could it be that with the change from string to array `related.issn` is not indexed anymore: https://github.com/hbz/lobid-resources/pull/1267

**Comment by blackwinter** [comment]
These tests illustrate that there's no normalization happening for ISSNs (in contrast to ISBNs). So if you changed the data, just adjust the tests accordingly (the new behaviour is the expected behaviour).

**Comment by TobiasNx** [comment]
I updated one test. It seems that the hyphen normalization is not supported for related.issn

**Comment by dr0i** [comment]
You didn't update:
> [error] Test tests.IndexIntegrationTest.testResultCount[(84) {Q=q.all:0720\-6763}] failed: expected:<[1]> but was:<[0]>

i.e. `0720-6763` cannot be queried. Idk if this is something that you want to work?

**Comment by TobiasNx** [comment]
> Idk if this is something that you want to work?

ISSNs are usually with `-` as ISBNs therefore ISSN with and without `-` should work.

**Comment by blackwinter** [comment]
> Also it has a - which should be deleted.

Why is that?

> ISSNs are usually with `-` as ISBNs therefore ISSN with and without `-` should work.

So add both. It's an array now after all.

**Comment by TobiasNx** [comment]
> > Also it has a - which should be deleted.
> 
> Why is that?
> 
> > ISSNs are usually with `-` as ISBNs therefore ISSN with and without `-` should work.
> 
> So add both. It's an array now after all.

This is the same situation with ISBN isn't it? We only use the ISBN without `-`. The same is the "historical" situation with ISSN.
https://github.com/hbz/lobid-resources/blob/7f982c13a25f9d6a4ef1a2c81a3749cf1cdaed36/src/main/resources/morph-hbz01-to-lobid.xml#L7557-L7559

**Comment by TobiasNx** [comment]
This can wait until after your holiday.
https://github.com/hbz/lobid-resources/commit/d167733d6a40890157d2120db1a3479b97bc65e1

this seems to be the commit. also we we already normalize the issn for the record: 
https://github.com/hbz/lobid-resources/blob/7c2be2679911cfea3b3a4416e10ce530db22baec/src/main/resources/alma/fix/identifiers.fix#L78

Also I do not see how this is any different to ISBN or why this is handled differently to ISBN: 
https://github.com/hbz/lobid-resources/blob/27e0915ba480df6ee6ff7315c11e00e0a5c3d835/web/test/tests/IndexIntegrationTest.java#L118-L120

There we also do not keep the hyphen.

**Comment by blackwinter** [comment]
Sorry, that's not what I meant with "normalization". I was talking about the `standardnumber` filter.

As I said before:

> just adjust the tests accordingly (the new behaviour is the expected behaviour)

**Comment by TobiasNx** [comment]
Ah, I see what the reason was. `related.isbn` and `realted.issn` were not configured in the same way in the `index-config,json` as `issn` and `isbn`. I commited a change for the index config.

**Comment by dr0i** [comment]
@TobiasNx will adopt the test to reflect a  `related.issn` query. Besides this the PR is good.

**Comment by TobiasNx** [comment]
@dr0i could you have another look?

**Comment by dr0i** [comment]
> Okay, I understand. But we don't want ISSN normalization in `q.all`, this is what got us in trouble with hbz IDs (see [2f45f28](https://github.com/hbz/lobid-resources/commit/2f45f288dcc7d3e963da0a3af41fa6a37c30b491)).

Do you ACK @TobiasNx ? We won't be able to query an ISSN with a hyphen.

@blackwinter but the same is OK for ISBN? (Look at https://github.com/hbz/lobid-resources/commit/2f45f288dcc7d3e963da0a3af41fa6a37c30b491 and test if `q.all=HT0702075558` hits - it does!)

**Comment by blackwinter** [comment]
> We won't be able to query an ISSN with a hyphen.

You're not using the query field `q.all`, are you?

> but the same is OK for ISBN? (Look at [2f45f28](https://github.com/hbz/lobid-resources/commit/2f45f288dcc7d3e963da0a3af41fa6a37c30b491) and test if `q.all=HT0702075558` hits - it does!)

`HT0702075558` is not a valid hbz ID, these only have 9 digits (so far).

**Comment by TobiasNx** [comment]
I am confused what is blocking the PR:
 Original intention of this PR was:
1) To change the `related.issn`-element to an array as the top-level `issn`-element already is (as well as `isbn` and `related.isbn` are). (3b710e2b2212bedea139d83da4655033c67fea08)
2) Also to delete the hyphen as we already do with the `issn`-element (as well as with `isbn` and `related.isbn`). (3b710e2b2212bedea139d83da4655033c67fea08)
3) To ensure that one can search for records with an issn with and without hyphen I changed the index config (18b55a70fa1db7231b77d8b23856b541863d1d94) and added a new test (d391be82cf4f08cdc80381c4b727039fafe4f66b).

This should be reflected in the 3 commits (not counting the merge).

Anything wrong with this?

**Comment by blackwinter** [comment]
> I see that the test still fails for the issn with hyphen using `q.all`:

As I said before, you have to adjust the tests to match your change in the data. Basically, you have to switch the results for `q.all:07206763` and `q.all:0720-6763`. You only did the first half so far.

These tests show that it's a behaviour change, but DigiBib (union catalogue) has to live with it I suppose.

**Comment by blackwinter** [comment]
> But with the isbn it works:

ISBNs receive special treatment via the `digibib_standardnumber` filter.

**Comment by TobiasNx** [comment]
Talked to @blackwinter off board.

Queries with `q.all `are not the general lobid search but a specific DigiBib-Search.
I added issn and related.issn tests.

Now the test should work.

**Comment by blackwinter** [comment]
> Now the test should work.

There are still some failures. Will review when everything passes.

**Comment by TobiasNx** [comment]
@dr0i can you have a look. It seems the indexIntegration tests work locally but the tests still seem to fail.

**Comment by dr0i** [comment]
@blackwinter you can have a look now

**Review by blackwinter — APPROVED** [review]

**Review by dr0i — APPROVED** [review]

**Comment by dr0i** [comment]
Will be deployed next Monday.

**Pull request merged**
