### PR TITLE
1803-callNumberN

### PR DESCRIPTION
**Pull request by TobiasNx**
As submitted from S.S. per mail and analysed by @blackwinter: The callNumber in $c can be duplicate but the item callNumber  $n cannot therefor we should prefer $n

### CODE REVIEW

**Comment by blackwinter** [comment]
I [repeat](https://github.com/hbz/lobid-resources/issues/1803#issuecomment-1598731926): Shouldn't we await the outcome of the FEx meeting next month?

**Comment by TobiasNx** [comment]
@blackwinter changed the transformation as discussed with FEx.

**Review by blackwinter — APPROVED** [review]
Tests need to be updated though.

**Comment by TobiasNx** [comment]
I dont know how to update the playtest, unfortunately....

**Comment by blackwinter** [comment]
@TobiasNx: Would pull request #1841 help you here?

**Comment by TobiasNx** [comment]
@dr0i can you fix the play tests

@blackwinter when @dr0i shows me how and if your ticket  #1839 is done?

**Pull request merged**
