### PR TITLE
Reuse nwbib fix for #1992, #1951 and  #1829

### LINKED ISSUE #1951: ISBN of related resources in GUI
e.g. http://lobid.org/resources/990366384450206441: displayed ISBN from "related" : 

> [ {"note" : [ "Online-Ausgabe" ],"label" : "Pest und Corona", "isbn" : [ "9783451821677", "3451821672" ]
instead of 
> "isbn" : [ "9783451388798", "3451388790" ]

### LINKED ISSUE #1992: Linked "Bände" and "Enthält" are not in GUI ALMA

### PR DESCRIPTION
**Pull request by TobiasNx**
Resolves #1951 and  #1829 Wrong ISBN and ISSN

and also fixes #1992 missing linking to Bände and Enthält

https://github.com/hbz/nwbib/issues/636

### CODE REVIEW

**Comment by fsteeg** [comment]
Build in GitHub Action fails, the change does not compile. You should always test locally (`sbt run` in `web/`) before pushing, and check the GitHub Action before opening a PR.

**Comment by TobiasNx** [comment]
@fsteeg you are right. It does not compile and the solution is not as easy as just copying the lines from the nwbib project. I assume that the failed compiling is due to nwbib still using JAVA 8 and lobid JAVA 11

**Comment by fsteeg** [comment]
> I assume that the failed compiling is due to nwbib still using JAVA 8 [...]

You can see the error in the build log of the GitHub Action:

https://github.com/hbz/lobid-resources/actions/runs/10678801716/job/29596615852?pr=2067#step:10:900

The problem seems to be the actual code change.

> the solution is not as easy as just copying the lines from the nwbib project

Yes, but if you have it running locally I'm sure we can set it up together.

**Comment by TobiasNx** [comment]
@fsteeg now it should work.

**Comment by TobiasNx** [comment]
Had a look at Table row values that is called for ISBN and ISSN, NwBib seems to differ a lot from lobid. I am not sure how to solve this any further.

**Comment by fsteeg** [comment]
I've replaced the `jsonVal` block with the nwbib version: https://github.com/hbz/lobid-resources/pull/2067/commits/fcf01f4bc020cef8a3805c81a8d44aea99f93bb7

Seems good now, e.g.: https://test.lobid.org/resources/990366384450206441

**Pull request merged**
