### PR TITLE
Replace FRBR with bibframe

### LINKED ISSUE #204: Replace FRBR "Item" class + properties with bibframe
FRBR still occurs four times in the JSON-LD context. We have already removed `frbr:Manifestation` (see https://github.com/lobid/lodmill/issues/639) and I suggest to replace the rest with Bibframe:

- http://purl.org/vocab/frbr/core#Item -> http://id.loc.gov/ontologies/bibframe/Item
- http://purl.org/vocab/frbr/core#exemplarOf -> http://id.loc.gov/ontologies/bibframe/itemOf
- http://purl.org/vocab/frbr/core#exemplar -> http://id.loc.gov/ontologies/bibframe/hasItem
- http://purl.org/vocab/frbr/core#owner -> http://id.loc.gov/ontologies/bibframe/heldBy

I guess the mapping above is correct. I had some problems with the definition of `bf:itemOf` and `bf:hasItem`, though, see http://listserv.loc.gov/cgi-bin/wa?A2=ind1702&L=bibframe&T=0&P=1431. We should wait for the response to my mail before we implement this.

### PR DESCRIPTION
**Pull request by ChristophEwertowski**
Replace FRBR "Item" class and properties "exemplarOf", "exemplar" and "owner"
with bibframe class and properties.

Because of the mass of the changes (i.e. all exemplars in all files) I didn't look at all of them. Since nothing was added but only replaced there shouldn't be errors in the bigger files.

Resolves #204

### CODE REVIEW

**Comment by dr0i** [comment]
There are conflicts - reassigning.

**Comment by ChristophEwertowski** [comment]
Note: The reverseTest files look good. All is changed as wanted. But for some unknown reason in the hbz01.es.nt there are 6000 lines less than in the master. Looking at it tomorrow.

**Comment by dr0i** [comment]
Aye - the URL property (`exemplarOf`) to identify the the title resource belonging to an item is hard encoded in a java class. Changed it to `itemOf`, amended and force-pushed the commit. Tests build properly now.
Reassigning for review.

**Comment by ChristophEwertowski** [comment]
Why are there deleted jsonld test files? (HT013480902 HT019093814  HT018612706:DE-Due18:In%20Bearbeitung  )

**Comment by dr0i** [comment]
Re: deleted test files:  they don't reside in the hbz01XmlClobs.tar.bz - which is the source of all the transformation tests. I think they are a relict of the other merged repo, now unused.
Considering this, one could argue to rather add them to the source files than to remove them. Did so just yet. Reassigning.

**Comment by dr0i** [comment]
Re removed " HT018612706:DE-Due18:In%20Bearbeitung": this `item` is no longer part of the latest `resource` HT018612706, so it will stay removed.

**Comment by ChristophEwertowski** [comment]
+1 
@acka47 Please review it as soon as possible. Otherwise we run in errors for each data change because of the missing/removed json files.

**Comment by acka47** [comment]
+1

**Comment by dr0i** [comment]
Reverted teh merge: this has to be first deployed to staging and then switched as a whole thus keeping coherent data. Needs possibly adjustments on the web application as well.

**Pull request merged**
