### PR TITLE
239 regroup publication information

### LINKED ISSUE #239: Regroup publication information
Taken from the discussion in https://github.com/hbz/lobid-resources/issues/59#issuecomment-279744128 ff.

**Example [HT002213253](http://lobid.org/resources/HT002213253)**

Current [JSON-LD](http://lobid.org/resources/HT002213253?format=json) (snippet):

```json
"publication":[
   {
      "endDate":"1934",
      "location":"Berlin",
      "publishedBy":"Weidmann",
      "startDate":"1934",
      "type":[
         "PublicationEvent"
      ]
   }
],
"publicationFrequency":[
   {
      "id":"http://marc21rdf.info/terms/continuingfre#i",
      "label":"dreimal wöchentlich"
   }
],
"secondaryPublication":{
   "description":[
      "Mikrofilm-Ausg.",
      "Berlin : Staatsbibliothek zu Berlin, 1999"
   ],
   "location":"Berlin",
   "publishedBy":"Staatsbibliothek zu Berlin",
   "startDate":"1999",
   "type":[
      "PublicationEvent"
   ]
}
```

Desired JSON:

```json
"publication":[
   {
      "endDate":"1934",
      "location":"Berlin",
      "publishedBy":"Weidmann",
      "startDate":"1934",
      "type":[
         "PublicationEvent"
      ],
      "frequency":{
         "id":"http://marc21rdf.info/terms/continuingfre#i",
         "label":"dreimal wöchentlich"
      }
   },
   {
      "description":[
         "Mikrofilm-Ausg.",
         "Berlin : Staatsbibliothek zu Berlin, 1999"
      ],
      "location":"Berlin",
      "publishedBy":"Staatsbibliothek zu Berlin",
      "startDate":"1999",
      "type":[
         "SecondaryPublicationEvent"
      ]
   }
]
```

This basically means to change x things:

- [ ] rename `publicationFrequency` to `frequency` and put the frequency object into the `PublicationEvent` object
- [ ] remove `secondaryPublication` property and add the secondary publication object to the `publication` array
- [ ] type secondary publication as `SecondaryPublicationEvent`

### PR DESCRIPTION
**Pull request by ChristophEwertowski**
Resolves #239

### CODE REVIEW

**Comment by fsteeg** [comment]
Seeing the new/changed `publicationHistory` field, would it make sense to nest that too as `publication.history`?

**Comment by acka47** [comment]
I second @fsteeg's proposal. Taking a deeper look at `publicationHistory`/[`rdau:P60538`](http://rdaregistry.info/Elements/u/P60538) (source: field 523) I see some problems:

- The property doesn't really fit the content as this is about frequency ("Relates a resource to an interval at which an issue or part of a serial or an update to an integrating resource is issued.").
- Looking at some example content of this field, the content seems to be quite diverse. Some examples: "Teils fehlerhafte H.-Zählung", "Periodizität: unregelmäßig", "Ab 1987,9 fehlerhafte Jg.-Zählung. - Periodizität: monatl.", "Erschienen: 1 (1874) - 6 (ca. 1877)", "Wöchentl", "Ersch. unregelmäßig", "Periodizität: 6x wöchentl.; anfangs 2x wöchentl.", "H. 580-599 in der Zählung übersprungen; Periodizität: monatl.", "13.1997,9 fälschlich als Jg. 12 gez. - Periodizität: monatl.", "Nr. 117 in d. Zählung übersprungen; Nr. 118-125 doppelt gez", "Erschienen: 1.1847 - 3.1849", "Übernimmt die Zählung des Vorgängers", "Mit Lfg. 3 (1999) Erscheinen eingestellt" and – my favorite "Späteres online über Internet; Adresse: URL: http://www.bfai.de; ersch. jährl."

The content often is – partyl –  about frequency. However, as the comment sar equite diverse, I suggest adding this information to the `publication` object with the `note` property.

**Comment by ChristophEwertowski** [comment]
Fails because the test can't find an incremental compiler and gets no output in under 10 minutes. Since I didn't delete the compiler I don't know how the first error occurs. Also I don't see a reason for the second one.

**Comment by ChristophEwertowski** [comment]
Now it hasn't got any conflicts anymore and the tests pass. So @fsteeg : Please deploy it for functional review.

**Comment by fsteeg** [comment]
Deployed to test:
http://test.lobid.org/resources/search?q=publication.note%3A*&format=json

**Comment by acka47** [comment]
+1

**Pull request merged**
