### PR TITLE
Rename subjectLabel to subjectAltLabel

### LINKED ISSUE #325: Rename subjectLabel to subjectAltLabel
See https://github.com/hbz/lobid-resources/issues/197#issuecomment-287703813

### PR DESCRIPTION
**Pull request by ChristophEwertowski**
Resolves #325

### CODE REVIEW

**Comment by dr0i** [comment]
The base of this should be chained to the other branches, see in `deploy` column. Base would be `72-MARCRelatorCodesInMABRDA` to seemlessly be able to be deployed.

**Comment by ChristophEwertowski** [comment]
I don't understand. For me the chain isn't broken: 325 should be merged into 3, which should be merged into 72, which should be merged into 200.

**Comment by dr0i** [comment]
Ah, yes now I see: in #320 branch 3 should be merged into branch 72. Since this PR wasn't asigned to anybody (i.e.: me) it looked like a broken "merge chain".

**Comment by dr0i** [comment]
+1

**Comment by dr0i** [comment]
Merged into master, see https://github.com/hbz/lobid-resources/commit/f25abc029588695e5597e043601f8962e270d671.

**Comment by dr0i** [comment]
Deployed to production, see http://lobid.org/resources/HT013577568?format=json.

**Pull request closed without merging**
