### PR TITLE
Cache table "isil2opac_hbzid"

### PR DESCRIPTION
**Pull request by dr0i**
Don't make a URL lookup to get the concordance every time an item is shown. Load thie concordance from a gitsubmodule table and cache it as HashMap.

Follows #1893.

### CODE REVIEW

**Comment by fsteeg** [comment]
Loading the file in `Global` and setting a static field on the `Lobid` controller seems more complicated than needed. Play has a built-in cache which I think would make sense to use here. It's already used elsewhere in the controller, see: https://github.com/hbz/lobid-resources/blob/880219bc02d119c5422ab6412dc33364440a6663/web/app/controllers/resources/Lobid.java#L148

**Comment by dr0i** [comment]
I don't think this makes sense as it would invoke the loading of the file hundreds of time.
I think play's cache makes sense for caching websites, not files. Or have I missed something?

**Comment by fsteeg** [comment]
Well it would load the file only once, and after that use the cached version. It's not about a browser cache it that's what you are thinking of. It's a server side cache.

**Comment by TobiasNx** [comment]
@dr0i @fsteeg I am not sure I we should proceed with this PR because we are about to add this info to the record metadata: #1888 and #1906

**Comment by dr0i** [comment]
Definitely not :) . See #1868.
Closing.

**Pull request closed without merging**
