### PR TITLE
Replace library with schema.org Game class

### LINKED ISSUE #235: Replace library:Game with schema:Game

### PR DESCRIPTION
**Pull request by ChristophEwertowski**
Resolves #235.
Merge after #233 is done.

### CODE REVIEW

**Comment by acka47** [comment]
I noticed that you used the "https" URI for the schema.org class. We decided on sticking to http URIs in the RDF, see https://github.com/hbz/lobid-organisations/issues/263. Reassigning @ChristophEwertowski .

**Comment by ChristophEwertowski** [comment]
Switched to http protocoll. Amended commits.

**Comment by acka47** [comment]
+1

**Comment by dr0i** [comment]
Closed because merged into master.

**Pull request closed without merging**
