### PR TITLE
Add missing hbz-URLs to predecessor and successor

### PR DESCRIPTION
**Pull request by ChristophEwertowski**
Resolves https://github.com/hbz/lobid-resources/issues/775

### CODE REVIEW

**Comment by dr0i** [comment]
+1
A question is arising when comparing `succesor/predecessor.label` to the one mentioned in #367: at the moment these labels are indexed meaning they are not only shown but also queriable (and queried when doing an `_all` query, weighted the same as e.g. the `title` field _if_ not otherwise declared within in the query which could be answered by @fsteeg ). Question is: is this ok so?

**Comment by ChristophEwertowski** [comment]
If we don't show a property in the frontend we shouldn't have it indexed. But since the `successor/predecessor.label` is an important information it should be indexed, shown and have links which redirect to the resource (if we have a lobid-URL of course). I don't think the `successor/predecessor.id` has to be indexed. What do you think, @acka47 ?

**Comment by dr0i** [comment]
> If we don't show a property in the frontend we shouldn't have it indexed. 

Not true in general , note to clarify possible misunderstandings: 
You _can retrieve_ data _without having it indexed_. By _indexed_ it is meant that you can also _search_ for it.

**Comment by ChristophEwertowski** [comment]
We will let them indexed. For looking at the index see https://github.com/hbz/lobid-resources/issues/782.

**Comment by dr0i** [comment]
Deployed to production, see e.g. http://lobid.org/resources/HT000009600.json. Closed.

**Pull request merged**
