### PR TITLE
1478-rpbVocabs

### LINKED ISSUE #1478: Add RPB Vocabs to ALMA-Fix
@acka47 noticed [here](https://github.com/hbz/lobid-resources/pull/1461) that RPB should already be included in FIX:

>The classification called "Rheinland-Pfälzische Bibliographie" we do have a SKOS version at https://w3id.org/lobid/rpb2.
>However, this actually is not related to RPB, see https://jira.hbz-nrw.de/browse/RPB-7 where it reads:
> >Bei der Systematik https://w3id.org/lobid/rpb2, die derzeit "RPB-Sachgruppen und Zusätze" heißt, handelt es sich um LBZ-Fachnotation, die mit der RPB eigentlich gar nichts zu tun haben.

>There obviously went something wrong in the past that this is associated with RPB at different places. However, we can add those URIs in the `id` field in lobid.

### PR DESCRIPTION
**Pull request by TobiasNx**
Resolves #1478

### CODE REVIEW

**Comment by acka47** [comment]
+1 Looks good to me but some checks are failing. We should wait until the afternoon with merging it anyway. Hopefully LBZ will deliver a correct name for RPB2 (currently "RPB-Sachgruppen und Zusätze") until then.

**Review by dr0i — APPROVED** [review]
+1

**Comment by TobiasNx** [comment]
Do not merge yet. I want to adjust some Documentation first.

**Comment by TobiasNx** [comment]
@dr0i you can merge

**Comment by dr0i** [comment]
Will be deployed next Monday.

**Pull request merged**
