### PR TITLE
Add another logging destination; switch logger 

### PR DESCRIPTION
**Pull request by dr0i**
- switch to logback
- keep log4j2 because of elasticsearch local node, see https://discuss.elastic.co/t/classcastexception-in-estestcase-slf4j/69040
- introduce logging of ETL to a separate file
- introduce logging of elasticsearch to a separate file
- change log pattern to be more concise
- exclude some logging libraries from dependencies
- add missing log messages

See #1847.

### CODE REVIEW

**Comment by dr0i** [comment]
functional review: @TobiasNx 
code review: @fsteeg 

@TobiasNx: test it like this:
1. `mvn clean install; cd web; sbt clean ; sbt test ` . Have a look in `web/logs` to see at least `application.log` and `elasticsearch.log` be filled.
2. To test the ETL log, first do 1) and then in `web` directory: ` sbt "start 7200";  curl http://localhost:7200/resources/webhook/update-alma?token=123 `. Now the `etl.log` should be filled too.

**Comment by TobiasNx** [comment]
+1

**Comment by TobiasNx** [comment]
You need to update the email reminder

**Comment by dr0i** [comment]
> Looks good. I'm a bit surprised by the removal of the (not logging-related) `jena-arq` and `httpclient` dependencies, but maybe they were simply unused.

Yes,` mvn dependency:tree -Dverbose` revealed  that it's "omitted for duplicate"  as it's already part of `org.metafacture:metafix`.

**Comment by dr0i** [comment]
Had to reintrocude jboss logging for play couldn'T be started otherwise on servers.

**Comment by dr0i** [comment]
Adjusted scripts and crontab, see #1933.

**Pull request merged**
