### PR TITLE
1248 contributor roles

### PR DESCRIPTION
**Pull request by TobiasNx**
See #1248
Until now we have only cre (label: Autor/-in), oth (Mitwirkende) But there are many more marc relators which seem to be used.

Questions:
- Are the code always [marc relators](https://id.loc.gov/vocabulary/relators.html)?
- How do we handle contributors with more than one role? See HT019246898 We need an array perhaps.
- How do we provide labels, is there a mapping list?

### CODE REVIEW

**Comment by acka47** [comment]
I'll try to answer your questions here:

### Are the code always [marc relators](https://id.loc.gov/vocabulary/relators.html)?

I am quite sure that they are.

### How do we handle contributors with more than one role? See HT019246898 We need an array perhaps.

See e.g. https://github.com/hbz/lobid-resources/issues/933#issuecomment-431770264 that links to more sources. I'll repeat what I wrote in https://github.com/hbz/lobid-resources/issues/868#issuecomment-405514382 here:

> In 2016 I asked on the Bibframe list how to record multiple contributions by the same person. Ray Denenberg of LoC [responded](https://listserv.loc.gov/cgi-bin/wa?A2=ind1612&L=BIBFRAME&D=0&P=13768):
>
>> If you want to list two roles, e.g. “illustrator” and “author” for the same person, the rule is, declare two separate Contribution resources.   Two or more role statements within the same Contribution resource should occur only because you want to provide two different representations (e.g. two different URIs) for the same role. 

### How do we provide labels, is there a mapping list?

The labels for MARC relators and many other controlled terms are configured in the [labels.json](https://github.com/hbz/lobid-resources/blob/master/src/main/resources/labels/labels.json).

**Comment by dr0i** [comment]
As @acka47 notes we need to use the `labels.json`. The file is used by `JsonLdEtikett` which we have to configure as receiver after `JsonEncoder`. The `JsonLdEtikett` will ensure that every object with an `id` has a label based on the definitions in `labels.json`. If no explicit definition is found a fallback is used to generateautomatically  a more-or-less fitting label. Main idea is to _always_ have provide a label.

**Comment by TobiasNx** [comment]
> As @acka47 notes we need to use the `labels.json`. The file is used by `JsonLdEtikett` which we have to configure as receiver after `JsonEncoder`. The `JsonLdEtikett` will ensure that every object with an `id` has a label based on the definitions in `labels.json`. If no explicit definition is found a fallback is used to generate automatically a more-or-less fitting label. Main idea is to _always_ provide a label.

But this is a "global" issue for the ALMA morph right? If we use the labels.json we would need to more than just the creator rol labels, right?

**Comment by TobiasNx** [comment]
Concerning the multiple roles that seems to be difficult to me to model, since the roles appear in a single field 100/110/700/710 as multiple subfields:
e.g. HT019246898
```
  <datafield tag="700" ind1="1" ind2=" ">
    <subfield code="a">Abel, Alexandra</subfield>
    <subfield code="0">(DE-588)1069204668</subfield>
    <subfield code="4">edt</subfield>
    <subfield code="4">aut</subfield>
    <subfield code="0">(uri) https://portal.dnb.de/opac.htm?method=simpleSearch&amp;cqlMode=true&amp;query=idn=1069204668</subfield>
    <subfield code="0">(uri) http://viaf.org/viaf/sourceID/DNB|1069204668</subfield>
    <subfield code="B">GND-1069204668</subfield>
  </datafield>
  <datafield tag="700" ind1="1" ind2=" ">
    <subfield code="a">Rudolf, Bernd</subfield>
    <subfield code="0">(DE-588)1038489679</subfield>
    <subfield code="4">edt</subfield>
    <subfield code="4">aut</subfield>
    <subfield code="0">(uri) https://portal.dnb.de/opac.htm?method=simpleSearch&amp;cqlMode=true&amp;query=idn=1038489679</subfield>
    <subfield code="0">(uri) http://viaf.org/viaf/sourceID/DNB|1038489679</subfield>
    <subfield code="B">GND-1038489679</subfield>
  </datafield>
  ```

**Comment by dr0i** [comment]
Don't knowexactly what you mean with "global". It's just that EtikettMaker would ensure to have a `label` for every entity having an `id``(this was also coined as the "sidecar approach" because every id would have a label). _If_ there is already a label for an id, created in the morph, this morphed label has precedence.
So, we only _gain_ with EtikettMaker.
And yes, if there is an id like a marc relator which is _not_ defined in labels.json and has _not_ been giben a label through the morph there is only a fallbal label created which we may not like very much. We will see this when implemented in the resulting json.

**Comment by acka47** [comment]
> Concerning the multiple roles that seems to be difficult to me to model, since the roles appear in a single field 100/110/700/710 as multiple subfields:

Isn't this analogous to the Aleph XML data that we already process for lobid-resources where also different relator codes are repeated in subfield `4`? See e.g. [HT018857620](https://lobid.org/hbz01/HT018857620) (snippet):

```xml
  <datafield tag="100" ind1="b" ind2="1">
  <subfield code="p">Barenboim, Daniel</subfield>
  <subfield code="d">1942-</subfield>
  <subfield code="4">cnd</subfield>
  <subfield code="3">Dirigent</subfield>
  <subfield code="4">drt</subfield>
  <subfield code="3">Regisseur</subfield>
  <subfield code="9">(DE-588)118506560</subfield>
</datafield>
```

Maybe a look into the hbz01-to-lobid morph makes sense. https://github.com/hbz/lobid-resources/pull/881 is the PR in which the transformation of multiple roles for one agent was implemented. Here is the diff in the morph: https://github.com/hbz/lobid-resources/pull/881/files#diff-c79e89b206237040d700b790040652e320068ef3301084a46eeee16cb715d952

**Comment by TobiasNx** [comment]
> Don't knowexactly what you mean with "global". It's just that EtikettMaker would ensure to have a `label` for every entity having an `id``(this was also coined as the "sidecar approach" because every id would have a label). _If_ there is already a label for an id, created in the morph, this morphed label has precedence.

I wanted to say, that since the EtikettMaker is not used at all at the moment, we provide labels always through the morph. To indtroduce the EtikettMaker as it worked before with Aleph we would check the morph if we need to delete the label provided by the morph. So that would be an issue for itself to introduce the EtikettMaker and update the workflow.

**Comment by dr0i** [comment]
With https://github.com/hbz/lobid-resources/pull/1263 the EtikettMaker is part of the flow.
With it comes the automatic creation of the `web/conf/context.jsonld` (running the test as usually is enough) - which is a nice thing, since it also makes it clear that this `context.jsonld` depends on the `labels`.

**Comment by TobiasNx** [comment]
this PR is replaced by #1266

**Pull request closed without merging**
