### PR TITLE
Tweak typo in successor transformation #1475

### PR DESCRIPTION
**Pull request by TobiasNx**
@acka47 hinted to this problem.

### CODE REVIEW

**Comment by acka47** [comment]
I just had the Maven build running but you beat me to it. Why do I not see the file `src/main/resources/alma/fix/relatedRessourcesAndLinks.fix` under "Files Changed"? This is strange.

**Comment by dr0i** [comment]
also all `succesor` fields seems to be just removed instead of fixing a type.

**Comment by TobiasNx** [comment]
it seems that I did not check them in.

**Review by dr0i — APPROVED** [review]

**Review by acka47 — APPROVED** [review]
+1

**Comment by dr0i** [comment]
Fixed, see e.g. http://test.lobid.org/resources/990053976760206441.json.

**Pull request merged**
