### PR TITLE
Normalize date of "issued"

### PR DESCRIPTION
**Pull request by dr0i**
See hbz/lobid-resources-web#18.

### CODE REVIEW

**Comment by acka47** [comment]
+1

**Comment by ChristophEwertowski** [comment]
+1

**Comment by dr0i** [comment]
Don't know why, but this didn't work, see e.g. http://staging.lobid.org/resources/HT004944075. "issued" totally missing here.

**Comment by dr0i** [comment]
Deployed to staging, see e.g. http://staging.lobid.org/resources/HT003104331 and http://test.lobid.org/resources/HT000398485.

**Comment by fsteeg** [comment]
+1

(I was unassigned before I reviewed this)

**Pull request merged**
