### PR TITLE
Add new roles chr, dnc, mod; expand regexes for roles; sort roles

### LINKED ISSUE #463: Add more instruments to corresponding role
Low priority. More instruments should be added as a criteria for http://id.loc.gov/vocabulary/relators/itr to assign people to the right roles. Listing missing instruments:
* clarinet (http://lobid.org/hbz01/HT019318164)
* guitar (http://lobid.org/hbz01/HT017716661)
* piano (http://lobid.org/hbz01/HT019318164)
* Violoncello (http://lobid.org/hbz01/HT018102322)

### PR DESCRIPTION
**Pull request by ChristophEwertowski**
Also remove superflous paratheseses.

Resolves #463

### CODE REVIEW

**Comment by acka47** [comment]
Travis checks have all failed. @ChristophEwertowski, you probably better take a look before we assign @dr0i .

**Comment by ChristophEwertowski** [comment]
The test resources were old so the comparison between them and the labels.json lead to an error.

**Comment by dr0i** [comment]
Deployed to production, closed.

**Comment by ChristophEwertowski** [comment]
Just some searches for the roles to see if they work and how many resources have agents with them:
"aft" / Autor des Nachwortes 2143 hits
"arr" / Arrangeur 5243 hits
"aui" / Einleitung 7698 hits
"aus" / Drehbuch 10031 hits
"lv#stageDesign" / Bühnenbild 4425 hits
"lv#choirTraining" / Choreinstudierung 2400 hits
"chr" / Choreographie 3371 hits
"clb" / Mitarbeit 45671 hits
"com" / Zusammengestellt von 3093 hits
"cmm" / Kommentar 846 hits
"col" / Sammler 7868 hits
"cst" / Kostümdesign 101 hits
"dgs" / Akademische Prüfungsperson 2549 hits
"dnc" / Tänzer 1279 hits
"fmd" / Filmdirektor 1134 hits
"isb" / Herausgebende Institution 18 hits
"itr" / Instrumentalist ~43000 hits
"lyr" / Lyriker 1323 hits
"mod" / Moderation 171 hits
"nrt" / Erzähler 1792 hits
"org" / Begründer ~45000 hits
"orm" / Organistator 8653 hits
"pro" / Produzent 1634 hits
"rcp" / Addressat 4006 hits
"sng" / Sänger 26316 hits
"spk" / Sprecher 9547 hits
"wat" / Zusätzlicher Text 1001 hits
"win" / Einleitung 1651 hits
"wpr" / Vorwort 3463 hits
"dgg" / Hochschule 16131 hits
"his" / Veranstaltende Institution 1104 hits

**Pull request merged**
