### PR TITLE
Add division joy for multithreading

### LINKED ISSUE #967: Use more cpu cores when using metafacture
Atm the ETL uses only one cpu core. As we need more than 25h to ETL the whole hbz catalog it would be nice to quicken this by using more cores.

There are two ideas:
1. maybe the `ObjectTee` can be used for demuxing
2. one could provide a plugin demuxing objects

### PR DESCRIPTION
**Pull request by dr0i**
This adds the ObjectDivider which (in conjunction with an ObjectPipeDecoupler
and added to a Tee) creates a multithreaded object pipeline.

- add 7 threads for transformation and indexing catalog data

Resolves #967.

### CODE REVIEW

**Comment by dr0i** [comment]
Reassigning myself since there are some minor things improvable, like declarations of variables and their naming, e.g. uppercasing. Readability of code can be improved but inserting line breaks.

**Comment by dr0i** [comment]
Added a simplified way to make threads. Depends on hbz/metafacture-core#10.

**Comment by fsteeg** [comment]
+1

Interesting stuff. Wondering if and where `ObjectPipeDecoupler` is/was used before.

**Comment by dr0i** [comment]
Deployed to production, closed.

**Comment by dr0i** [comment]
Ack. I couldn't find anything. Also, no tests! It's probably used _somewhere_, but as that code is not online it's like that useful class doesn't exist at all.

**Pull request merged**
