### PR TITLE
Add roles from every fourth subfield of persons and organistions

### LINKED ISSUE #72: Take into account MARC relator codes in RDA entries
Moved here from https://github.com/lobid/lodmill/issues/759. Sub-issue of https://github.com/hbz/lobid/issues/161, see https://github.com/hbz/lobid/issues/161#issuecomment-161566116.

We just have to take the code from subfield 4 in the 1*\* and 2*\* fields and append it to `http://id.loc.gov/vocabulary/relators/` to get the relator code for the respective entry. Default entry (at least for person) is `aut` but for now we will continue using `dct:creator`.

Examples:

http://lobid.org/resource/HT018772877, [source](http://beta.lobid.org/hbz01/HT018772877) (snippet):

``` xml
<datafield tag="100" ind1="b" ind2="1">
  <subfield code="p">Klein, Volkmar</subfield>
  <subfield code="4">edt</subfield>
  <subfield code="3">Herausgeber</subfield>
  <subfield code="9">(DE-588)174630727</subfield>
</datafield>
```

http://lobid.org/resource/HT018776405, [source](http://beta.lobid.org/hbz01/HT018776405) (snippet):

``` xml
<datafield tag="200" ind1="b" ind2="1">
  <subfield code="k">Theater im Pfalzbau</subfield>
  <subfield code="4">isb</subfield>
  <subfield code="3">Herausgebendes Organ</subfield>
  <subfield code="9">(DE-588)301289-X</subfield>
</datafield>
```

https://lobid.org/resource/HT018781534, [source](http://beta.lobid.org/hbz01/HT018781534) (snippet):

``` xml
<datafield tag="100" ind1="-" ind2="1">
  <subfield code="p">Schroeder, Hermann</subfield>
  <subfield code="d">1904-1984</subfield>
  <subfield code="4">cmp</subfield>
  <subfield code="3">Komponist</subfield>
  <subfield code="9">(DE-588)118823442</subfield>
</datafield>
```

https://lobid.org/resource/HT018782520, [source](http://beta.lobid.org/hbz01/HT018782520) (snippet):

``` xml
<datafield tag="104" ind1="a" ind2="1">
  <subfield code="p">Heitmann, Michaela</subfield>
  <subfield code="d">1969-</subfield>
  <subfield code="4">art</subfield>
  <subfield code="3">Künstler</subfield>
  <subfield code="9">(DE-588)142552739</subfield>
</datafield>
```

### PR DESCRIPTION
**Pull request by ChristophEwertowski**
Will resolve #72.

### CODE REVIEW

**Comment by ChristophEwertowski** [comment]
Unsuccessful tries with every fourth hit in the 100s and 200s (Ansetzungsform) and try for one specific resource. @dr0i : Do I have to define the source fields somewhere else too (didn't find anything) or did I miss something in the regexp?

**Comment by ChristophEwertowski** [comment]
It was the regex. In the test data set are four resources which possess the subfield of which two contain edt and two ctb (where the change can't be seen because contributor is the default). @dr0i : Please deploy it to the staging system for review of all roles in the subfields.

**Comment by dr0i** [comment]
@ChristophEwertowski : Deployed to test.

**Comment by dr0i** [comment]
Deployed to test, see e.g. http://test.lobid.org/resources/HT018939763.

**Comment by acka47** [comment]
The switch back to doing functional review on the issue doesn't work so good as we are not consistent recently in where we review. I  already reviewed this on test, see https://github.com/hbz/lobid-resources/issues/72#issuecomment-286690191 following.

**Comment by dr0i** [comment]
@acka47 we just talked about in the "stand up" and I was updated to how we review/deploy.

**Comment by dr0i** [comment]
+1

**Pull request closed without merging**
