### PR TITLE
307 remove computer carrier from online ressources

### LINKED ISSUE #307: Remove medium "computer carrier" from online resources
From https://github.com/hbz/lobid-resources/issues/298#issuecomment-285624228:

> I suggest removing the medium information http://rdaregistry.info/termList/RDAMediaType/1003 from all resources that have the medium http://rdaregistry.info/termList/RDACarrierType/1018 (Online Resource). This will be an improvement of faceting options.

### PR DESCRIPTION
**Pull request by ChristophEwertowski**
Resolves #307

### CODE REVIEW

**Comment by dr0i** [comment]
+1

**Comment by dr0i** [comment]
Deployed to test. Please review if UI needs update - if not reassign me to deploy. See e.g.
http://test.lobid.org/resources/HT010726584.

**Comment by acka47** [comment]
+1 No UI update needed. (Is it ok I review this in the PR?)

**Comment by dr0i** [comment]
@acka47 yes, ok to review in PR. You could also remove assignation of @ChristophEwertowski and label "review" and add label "deploy" . Label switch also on mother issues. Else I have to do it.

**Pull request merged**
