### PR TITLE
Add Subfield 689$p 

### PR DESCRIPTION
**Pull request by maipet**
#1972

### CODE REVIEW

**Review by acka47 — CHANGES_REQUESTED** [review]
Integration tests have to be adjusted because of the added test file, see https://github.com/hbz/lobid-resources/actions/runs/8139656167/job/22243316186#step:8:865 following. It probably makes sense when @dr0i shows you what to do, @maipet.

**Review by dr0i — APPROVED** [review]

**Comment by dr0i** [comment]
To see what play ("web") tests have to be adapted:
`git/lobid-resources/web/ $ sbt "test:testOnly *IndexIntegrationTest" | grep error `
Look at the complained numbers and increase them accordingly in ` git/lobid-resources/web/test/tests/IndexIntegrationTest.java`. Then run the test again until all is good.

**Review by acka47 — APPROVED** [review]
+1

**Comment by dr0i** [comment]
Will be deployed next Monday.

**Pull request merged**
