### PR TITLE
1373-PORasHasItemObject

### PR DESCRIPTION
**Pull request by TobiasNx**
Based on @acka47, @dr0i  and my considerations: [here](https://github.com/hbz/lobid-resources/issues/1177#issuecomment-809173419), [here](https://github.com/hbz/lobid-resources/issues/1373#issuecomment-1324698621) and [here](https://github.com/hbz/lobid-resources/issues/1373#issuecomment-1324828383) I have reintroduced `POR` as object of `hasItem`.

Things I have done that are new:
- introduce types schema.org `DigitalDocument` for POR and DC.terms `PhysicalObject` for ITMs
- build the POR id based on: `"http://lobid.org/items/[almaMmsId]:[ISIL]:[Portfolio PID $a]#!"` used the PID instead of the callNumber
- introduced the label "Electronic Portfolio"
- fixed the urls for `electronicLocator` and `sublocation` also see: https://github.com/hbz/lobid-resources/issues/1157

@acka47 , @dr0i and @hagbeck could you have a look, if this is sufficient for you?

### CODE REVIEW

**Comment by TobiasNx** [comment]
Note to myself: electronicLocator perhaps needs to be different, for POR $A: https://github.com/hbz/lobid-resources/issues/1157

**Comment by TobiasNx** [comment]
@dr0i and @acka47 said the direction is good. So I withdraw the draft status.
@hagbeck are the changes okay with you?

**Comment by hagbeck** [comment]
Seems to be ok.

**Comment by TobiasNx** [comment]
@dr0i since @hagbeck and @acka47 gave their okay. I suggest we could merge this if this is okay for you? Perhapse we need to adjust the Schema, but I would do that in another MR.

**Review by dr0i — APPROVED** [review]

**Pull request merged**
