### PR TITLE
745 change order of volume statement

### PR DESCRIPTION
**Pull request by ChristophEwertowski**
Resolves https://github.com/hbz/lobid-resources/issues/745

### CODE REVIEW

**Comment by dr0i** [comment]
Principally +1.
As there are tags introduced in e.g. HT004381366 `"numbering" : "<Tezemu>",` we should check if this doesn't make problems when viewing in our html frontend.
@ChristophEwertowski can you index a small test to check this?

**Comment by ChristophEwertowski** [comment]
It is already put on test.lobid.org, see http://test.lobid.org/resources/HT004381366 or http://test.lobid.org/resources/HT004381366.json.

**Comment by dr0i** [comment]
Ah, ok. But the newly introduced tags seems indeed to make troubles - see http://lobid.org/resources/HT004381366  "Band Tezemu" , whilst there is only "Tezemu" in http://test.lobid.org/resources/HT004381366. So there are at least two ways to fix this:
1. remove the tags from the data
2. fix the html-rendering in the frontend

I would propose to go with 1. because that help ALL possible HTML-frontends. Also, I think the `<>` don't serve any normal-human-understandable purpose, am I right?

**Comment by ChristophEwertowski** [comment]
Well, I only see the difference between "Tezemu" in production and "<Tezemu>" in test but no "Band Tezemu". Like it's in the [MAB-XML](http://lobid.org/hbz01/HT004381366). 
Supposedly "<Tezemu>" is how it's stated on or in the volume. On the frontend the sharp brackets are removed anyway, see the title field in [HT004381366 (test, frontend)](http://test.lobid.org/resources/HT004381366). So if it doesn't lead to indexing errors we should let it in the data with the brackets and in the frontend without it.

**Comment by dr0i** [comment]
Look at http://lobid.org/resources/HT004381366 , see column "Erschienen als". There is the "Tezemu".

**Comment by acka47** [comment]
Although I already gave my "+1", I am all for removing `<>` during the transformation (as I already said in the standup).

**Comment by ChristophEwertowski** [comment]
Brackets removed from RAK (subfield a) and RDA resources (subfield n). `curl 'http://weywot5.hbz-nrw.de:9200/resources-smalltest/resource/HT004381366' |json_pp ` gives the right results in `numbering` and `title` but the frontend hasn't catched up yet.

**Comment by dr0i** [comment]
+1

**Comment by dr0i** [comment]
> frontend hasn't catched up yet.
That's probably the cache. Could restart but that's not necessary since in your updated tests the problematic resource is gone for good.

**Comment by dr0i** [comment]
Deployed to production, se e.g. https://lobid.org/resources/HT003654516.json. Closed.

**Pull request merged**
