### PR TITLE
Rework morph

### PR DESCRIPTION
**Pull request by dr0i**
Adds some simplifictions to the morph while discussing the morph with @ChristophEwertowski. 
Adds some more culturegraph sameAs links.
Also fixes a problem within the tests.

### CODE REVIEW

**Comment by ChristophEwertowski** [comment]
Got a local copy to see why it didn't work. ```mvn clean install```and ```mvn test``` build but the marked command ```mvn clean install -e -q --settings settings.xml``` does not.

**Comment by dr0i** [comment]
I restarted the travis build and then it was succesful. Don't know why - sometimes travis seems to use some old cached stuff and then goes wild.
Re: --settings: works here. What error messages do you got?

**Comment by ChristophEwertowski** [comment]
I tried it again this morning and it worked. Was probably dependent on the -DgenerateTestData to be done first. +1

**Comment by dr0i** [comment]
Would love to reopened because it was accidentially merged (and undo that by force pushing the original branch again to master).
But it doesn't seem you can reopen PRs that have been closed and merged.

**Pull request merged**
