### PR TITLE
753 expand definition of nature of content

### LINKED ISSUE #753: Expand definition for natureOfContent
While working on https://github.com/hbz/lobid-resources/issues/592 I saw in a created file which counts the contents of MAB 064 that a lot of resources don't have `natureOfContent` which probably should.

From the [BVB documentation](https://www.bib-bvb.de/web/kkb-online/rda-mini-mab):
```
Angaben zur Art des Inhalts, erweiterte Datenträgertypen, musikalische Ausgabeform
Indikator:
blank = nicht definiert --- nicht verwenden!
a = Angaben zum Inhalt (gnd-content)
b = Angaben zum Datenträger (gnd-carrier)
c = Musikalische Ausgabeform (gnd-music)
```

Example for *ind1="c"*: http://lobid.org/hbz01/HT015509219
Example for *ind2="2"*: http://lobid.org/hbz01/HT015429988

### PR DESCRIPTION
**Pull request by ChristophEwertowski**
Resolves #753

### CODE REVIEW

**Comment by ChristophEwertowski** [comment]
Strange. The pull comparison doesn't work right. I also tried to resolve the conflict by using the hbz01XmlClobs and adding the missing example but that didn't lead to right result.

**Comment by ChristophEwertowski** [comment]
Probably the problem was resolved by merging the master into the branch.

**Comment by dr0i** [comment]
+1

**Comment by dr0i** [comment]
Deployed to production, see e.g. http://lobid.org/resources/HT018853619.json. Closed.

**Pull request merged**
