### PR TITLE
Ensure killing of web app

### PR DESCRIPTION
**Pull request by dr0i**
This may prevent some monit restart problems.
See mail "Lobid-resources web app unerreichbar für 5 Stunden"
from Fri, 27 Jul 2018 11:46:07 +0200 to lobid-admin.

Message ID: <0ef83206-bffb-418d-a847-aa728f9a1c21@hbz-nrw.de>

### CODE REVIEW

**Comment by fsteeg** [comment]
This will always run both `kill` and `kill -9`, right? Couldn't we then just run `kill -9` in the first place?

**Comment by dr0i** [comment]
Right, we could, but `kill` is a _graceful_ kill meaning that the web-app may do some things when going down (e.g., logging that it's going down), whilest `kill -9` is a brutal killing without giving the to be killed process time to pray.
So we try first to take down the process gracefully and wait a reasonable time before killing the process brutally if still standing.

**Comment by fsteeg** [comment]
Right, makes sense. +1

**Comment by dr0i** [comment]
Deployed. Closing.

**Pull request merged**
