### PR TITLE
Move date into `describedBy.resultOf.Object` #1470

### PR DESCRIPTION
**Pull request by TobiasNx**
I moved the dates as wished by @acka47 in #1470 one question though why do we format dates differently in `describedBy.resultOf.endTime`

`"endTime" : "0000-00-00T00:00:00"` is dateTime while `dateCreated` and `dateModified`: `YYYYMMDD` without `-`.

### CODE REVIEW

**Comment by acka47** [comment]
> why do we format dates differently in `describedBy.resultOf.endTime`
> 
> `"endTime" : "0000-00-00T00:00:00"` is dateTime while `dateCreated` and `dateModified`: `YYYYMMDD` without `-`.

This has historical reasons, I think. `YYYYMMDD` was used in the Aleph data. I agree it would be better to use ISO 8601 everywhere but I think this might break some clients...

**Comment by TobiasNx** [comment]
> > why do we format dates differently in `describedBy.resultOf.endTime`
> > `"endTime" : "0000-00-00T00:00:00"` is dateTime while `dateCreated` and `dateModified`: `YYYYMMDD` without `-`.
> 
> This has historical reasons, I think. `YYYYMMDD` was used in the Aleph data. I agree it would be better to use ISO 8601 everywhere but I think this might break some clients...

@acka47 : If we already break the API by moving the date why not change the date pattern anyway then?

**Comment by acka47** [comment]
>  If we already break the API by moving the date for ALMA FIX why not change the date pattern anyway then?

Of course, you are right. I forgot that we decided to move the date but this PR's title states it loud an clear. So please make it all ISO 8601.

**Comment by dr0i** [comment]
Breaking the pattern `YYYYMMDD` will probably break our deletions API and also maybe something like this:

*Working*:
http://alma.lobid.org/resources/search?q=describedBy.dateCreated:%3E20220110&format=json
http://lobid.org/resources/search?q=publication.startDate%3A%5B*+TO+1500%5D&format=json
http://lobid.org/resources/deletions/search?q=describedBy.deleted%3A%5B20180328+TO+20180405%5D

*Not working*:
http://alma.lobid.org/resources/search?q=describedBy.dateCreated:%3E%222022-01-10%22&format=json
http://lobid.org/resources/deletions/search?q=describedBy.deleted%3A[2018-03-28+TO+2018-04-05]
http://lobid.org/resources/search?q=publication.startDate%3A[*+TO+1500-01-01]&format=json

Maybe this is just a syntax thing, maybe an elasticsearch setting. Idk.

**Review by dr0i — APPROVED** [review]

**Review by dr0i — CHANGES_REQUESTED** [review]
Deletions API may  break if the field is moved.
Also API documentation would have to be updated.
Do we have an "API-break" tag? We could/should handle these questions later when switching this to our main product.

**Pull request merged**
